---
title: "SBF_Flakes"
format: html
editor: visual
---

```{r libraries}
#| warning: false
#| message: false

# To plot figures

library(ggplot2)
library(forcats)
library(ggpubr)
library(ggridges)
library(cowplot)
library(ggforce)

library(infer)
#library(rcompanion)
library(purrr)
library(modelr)
#library(rcompanion)
library(viridis)

library(scales)
library(stringr)

# To generate tables
library(gtsummary)
library(gt)
library(broom)
library(broom.mixed)

library(stargazer)
library(kableExtra)

# To tidy the data
library(tidyr)
library(tidyverse)
library(dplyr)
library(forcats)
library(tidybayes)

# Bayesian models
library(brms)
library(emmeans)
library(loo)
library(BayesFactor)
library(posterior)
```

```{r ReadData}
#| message: false
#| warning: false

# Read and clean data
df_sum24 <- read.csv("../data/AG_Summer2024_SBF_Final.csv") |>
  select(-c('X')) |>
  filter(RAWMATERIAL != "BWA UPPER 1" &
           RAWMATERIAL %in% c("Quartz", "Quartzite", "Silcrete")) |>
  mutate(#STRAT = ifelse(STRAT == "3a", "3", # combine strat 3a and 3b
          #              ifelse(STRAT == "3b", "3", STRAT)),
         STRAT_mod = ifelse(STRAT %in% c("5"), "Terrestrial",
                     ifelse(STRAT %in% c("4a", "4b"), "Mixed", "Coastal"))) |>
  mutate(STRAT = factor(STRAT),
         STRAT_mod = factor(STRAT_mod))

df_sum25 <- read.csv("../data/AG_Summer2025_SBF_Final.csv") |>
  filter(RAWMATERIAL != "BWA UPPER 1" &
           RAWMATERIAL %in% c("Quartz", "Quartzite", "Silcrete")) |>
  mutate(#STRAT = ifelse(STRAT == "3a", "3", # combine strat 3a and 3b
          #              ifelse(STRAT == "3b", "3", STRAT)),
         STRAT_mod = ifelse(STRAT %in% c("5"),"Terrestrial",
                     ifelse(STRAT %in% c("4a", "4b"), "Mixed", "Coastal"))) |>
  mutate(STRAT = factor(STRAT),
         STRAT_mod = factor(STRAT_mod)) |>
  
  select(-c(X))

# student's dataframe
df_One <- read_csv("../data/DataSheet_1.csv")|>
  mutate(STRAT = tolower(Layer),
         
         PLATFORMWIDTH = parse_number("Platform Width"),
         PLATFORMTHICKNESS = parse_number("Platform Thickness"),
         MAXLENGTH = parse_number("Maximum Length"),
         TECHLENGTH = parse_number("Technological Length"),
         MAXWIDTH = parse_number("Maximum Width"),
         TECHWIDTH = parse_number("Technological Width"),
         MAXTHICKNESS = parse_number("Thickness"),
         MASS = parse_number("Mass"))

df_One <- df_One[1:289,]

df_One_flakes <- df_One |>
  
  add_column(OTHERUNIT = NA, .before = "Raw Material") |>

  rename(SITE = Site, UNIT = Unit, NAMED_ID = `Other Name`,
         RAWMATERIAL = `Raw Material`, CORTEX = `Cortex Percent`,
         CORTEXTYPE = `Cortex Origin`, ARTIFACTCLASS = `Artifact class`,
         COMPLETENESS = Complete, PLATFORM = `Platform?`,
         FLAKEINITIATION = Initiated, FLAKETERMINATION = Termination,
         FLAKEGEOMETRY = `Flake Geometry`, PLATFORMPREP = `Platform Preparation`,
         PLATABRASION = PlatformAbrasion, 
         STAGE = `Flaking Stage`) |>
  
  select(-c(Layer, Notes, Photo,
            `Platform Width`:`Platform Thickness`, `Maximum Length`:Mass)) |>
  
  mutate(#STRAT = ifelse(STRAT == "3a", "3", # combine strat 3a and 3b
          #            ifelse(STRAT == "3b", "3", 
           #                  ifelse(STRAT == "5a", "5", STRAT))),
         STRAT_mod = ifelse(STRAT %in% c("5"),"Terrestrial",
                     ifelse(STRAT %in% c("4a", "4b"), "Mixed", "Coastal"))) |>
  mutate(STRAT = factor(STRAT),
         STRAT_mod = factor(STRAT_mod)) |>
  
  relocate(STRAT, .before = "UNIT") |>
  relocate(CORTEXTYPE, .before = "ARTIFACTCLASS")
  
  

# student's Dataframe
df_Two <- read_csv("../data/DataSheet_2.csv") |>
  
  rename(SITE = Site, STRAT = Layer, UNIT = Unit, NAMED_ID = `Other Name`,
         RAWMATERIAL = `Raw Material`, CORTEX = `Cortex Percent`,
         ARTIFACTCLASS = `Artifact class`, CORTEXTYPE = `Cortex Origin`,
         COMPLETENESS = Complete, PLATFORM = `Platform?`,
         FLAKEINITIATION = Initiated, FLAKETERMINATION = Termination,
         FLAKEGEOMETRY = `Flake Geometry`, PLATFORMPREP = `Platform Preparation`,
         PLATABRASION = `PlatformAbrasion`, PLATFORMWIDTH = `Platform Width`,
         PLATFORMTHICKNESS = `Platform Thickness`, STAGE = `Flaking Stage`,
         MAXLENGTH = `Maximum Length`, TECHLENGTH = `Technological Length`,
         MAXWIDTH = `Maximum Width`, TECHWIDTH = `Technological Width`,
         MAXTHICKNESS = Thickness, MASS = Mass) |>
  
  select(-c(`...2`,Notes:Photo))

df_Two_flakes <- df_Two |>
  
  add_column(OTHERUNIT = NA, .before = "RAWMATERIAL") |>
  
  mutate(#STRAT = ifelse(STRAT == "3a", "3", # combine strat 3a and 3b
          #          ifelse(STRAT == "3b", "3", 
           #                ifelse(STRAT == "5a", "5", STRAT))),
          STRAT_mod = ifelse(STRAT %in% c("5"),"Terrestrial",
                     ifelse(STRAT %in% c("4a", "4b"), "Mixed", "Coastal"))) |>
  mutate(STRAT = factor(STRAT),
         STRAT_mod = factor(STRAT_mod))




df_Two_flakes <- df_Two_flakes[1:421,] |>
  relocate(CORTEXTYPE, .before = "ARTIFACTCLASS")
  

df_students <- rbind(df_Two_flakes, df_One_flakes)


df <- rbind(df_sum24, df_sum25) |>
  merge(df_students, all = T) |>
  mutate(TECHLENGTH = as.numeric(TECHLENGTH),
         MAXWIDTH = as.numeric(MAXWIDTH),
         MAXTHICKNESS = as.numeric(MAXTHICKNESS)) |>
  filter(STRAT %in% c("1", "2", "3a", "3b", "3", "4a", "4b", "5")) |>
  
  mutate(ARTIFACTCLASS = ifelse(ARTIFACTCLASS == "flake", "Flake",
                         ifelse(ARTIFACTCLASS == "blade", "Flake",
                         ifelse(ARTIFACTCLASS == "Flake/Blade", "Flake",
                         ifelse(ARTIFACTCLASS == "Fragment", "Flake",
                                                     ARTIFACTCLASS)))),
         
         RAWMATERIAL = as.factor(
           ifelse(RAWMATERIAL == "Silcrete flake", "Silcrete",
                              ifelse(RAWMATERIAL == "OTHER", "Other",
                                     RAWMATERIAL))),
         
         CORTEX = ifelse(CORTEX == "10-40%", "11-40%",
                  ifelse(CORTEX == "90-99%", "91-99%",
                  ifelse(CORTEX == "60-90%", "61-90%",
                  ifelse(CORTEX == "40-60%", "41-60%",
                         CORTEX)))),
         
         STRAT_mod = ifelse(STRAT == "1", 27.2,
                     ifelse(STRAT == "2", 37.1,
                     ifelse(STRAT == "3a", 49.8,
                     ifelse(STRAT == "3b", 29.6,
                     ifelse(STRAT == "4a", 26.6,
                     ifelse(STRAT == "4b", 25.5,
                     ifelse(STRAT == "5", 8.4, 0))))))),
         
         STRAT_modn = ifelse(STRAT %in% c("5"),"Pre-Megamidden",
                     ifelse(STRAT %in% c("4a", "4b"), "Transitional", 
                            "Megamidden")),
         STRAT_modn = fct_relevel(STRAT_modn, 
                                  c("Pre-Megamidden", "Transitional",
                                    "Megamidden"))) |>
  
  filter(RAWMATERIAL %in% c("Quartz", "Quartzite", "Silcrete"),
         CORTEX != "\\",
         MAXWIDTH < 1250,
         MASS < 300)


# take average core flake scar length
df |>
  dplyr::filter(ARTIFACTCLASS=="Core") |>
  group_by(RAWMATERIAL, STRAT) |>
  summarize(Ave_FlakeLength = mean(LENGHTLONGESTFLAKESCAR)) -> core_size


# set values for small, medium, and large slug effect sizes

small <- 5.18


# Subset data by flakes and flake variables
core_bind <- full_join(core_size, df) |>
  filter(ARTIFACTCLASS == "Flake" & COMPLETENESS == "Complete") |>
  group_by(RAWMATERIAL, STRAT) |>
  mutate(Utility_small = TECHLENGTH*(TECHLENGTH - small),
         Utility_mid = TECHLENGTH*(TECHLENGTH - medium),
         Utility_large = TECHLENGTH*(TECHLENGTH - large),
         
         Transport_small = Utility_small/((MAXTHICKNESS/TECHLENGTH)*TECHLENGTH^3),
         
         Reduction = TECHLENGTH/Ave_FlakeLength) |>
  
  select(any_of(names(df_students)), c(Utility_small:Reduction), STRAT_mod,
         STRAT_modn) -> df.flakes

# Subset data by cores and core variables
df.cores <- df |>
  filter(ARTIFACTCLASS == "Core" & CORECOMPLETENESS == "Complete") |>
  mutate(SA_Ellipse = (4*pi)*
           ((((((MAXLENGTH/2)*(MAXWIDTH/2))^1.6075)+
           (((MAXLENGTH/2)*(MAXTHICKNESS/2))^1.6075)+
           (((MAXWIDTH/2)+(MAXTHICKNESS/2))^1.6075))/3)^(1/1.6075)))

# Subset data by retouch and retouch variables
df.retouch <- df |>
  filter(ARTIFACTCLASS == "RetouchedTool" & RAWMATERIAL != "BWA UPPER 1" &
           COMPLETENESS == "Complete") |>
  mutate(Utility_small = TECHLENGTH*(TECHLENGTH - small),
         
         Transport_small = Utility_small/((MAXTHICKNESS/TECHLENGTH)*TECHLENGTH^3)) |>
  select(1:11,21:27,29:60, Utility_small:Transport_small)

# Read tabulated data from previous publications (i.e. Jerardino & Yates)
sbf_df <- read.csv("../data/SBF_ToolType.csv") |>
  filter(Layer != "3b") |>
  mutate(STRAT_mod = ifelse(Layer == "1", 27.2,
                     ifelse(Layer == "2", 37.1,
                     ifelse(Layer == "3a", 49.8,
                     ifelse(Layer == "4a", 26.6,
                     ifelse(Layer == "4b", 25.5,
                     ifelse(Layer == "5", 8.4, 0)))))),
         
         STRAT_modn = ifelse(Layer %in% c("5"),"Pre-Megamidden",
                     ifelse(Layer %in% c("4a", "4b"), "Transitional", 
                            "Megamidden")),
         STRAT_modn = fct_relevel(STRAT_modn, 
                                  c("Pre-Megamidden", "Transitional",
                                    "Megamidden")))

sbf_un <- read.csv("../data/SBF_ToolType_unmod.csv") |>
  filter(Layer != "3b") |>
  mutate(STRAT_mod = ifelse(Layer == "1", 27.2,
                     ifelse(Layer == "2", 37.1,
                     ifelse(Layer == "3a", 49.8,
                     ifelse(Layer == "4a", 26.6,
                     ifelse(Layer == "4b", 25.5,
                     ifelse(Layer == "5", 8.4, 0)))))),
         
         STRAT_modn = ifelse(Layer %in% c("5"),"Pre-Megamidden",
                     ifelse(Layer %in% c("4a", "4b"), "Transitional", 
                            "Megamidden")),
         STRAT_modn = fct_relevel(STRAT_modn, 
                                  c("Pre-Megamidden", "Transitional",
                                    "Megamidden")))
```

## Toolkit composition

```{r fig-Figure10}

png("../results/figures/fig14.png", width = 185, height = 120,
    units = "mm", res = 300)
# Data pulled from Jerardino, 2022
sbf_df |>
  group_by(STRAT_mod) |>
  summarize(Tool_sum = sum(Count)) |>
  mutate(Lithic_Dens = c(602.7, 850.9,
                         ((819+1861)/((819/1863.6)+(1861/1094.7))),
                         2904.3, 1545.6, 2788.5),
         Dep_rate = abs(c(((2.45+2)/2)-((2.6+2.2)/2),
                      ((2.6+2.2)/2)-((3+2.4)/2),
                      ((3+2.4)/2)-((3.5+2.7)/2),
                      ((3.5+2.7)/2)-((5+3)/2),
                      ((5+3)/2)-(4.6),
                      ((9.7+4.6)/2)-(9.7))),
         STRAT_modn = c("Pre-Megamidden", "Transitional", "Transitional",
                        rep("Megamidden", 3))) |>
  left_join(
    
    sbf_un |>
      group_by(STRAT_mod) |>
      summarize(Deb_sum = sum(Count)) 
    
) |>
  mutate(Tool_Perc = (Tool_sum/Deb_sum)*100,
         Lithic_std = Lithic_Dens/Dep_rate) |>
  
  ggplot(aes(x = Lithic_std, y = Tool_Perc, color = STRAT_modn, 
             label = STRAT_mod))+
  geom_point(size = 3)+
  geom_text(aes(fontface = 2), hjust = 0.3, vjust = -0.5, size = 5,
            show.legend = F, color = "black")+
  scale_fill_viridis_d()+
  scale_color_viridis_d()+
  xlab("Lithic Density/Deposition Rate")+ylab("Formal Tool Percent")+
  theme_minimal()+
  theme(text = element_text(size = 20),
        legend.title = element_blank())+
    ylim(0, 11)

dev.off()
```

## Flake Descriptions

#### Platform abrasion

```{r}
df.flakes |>
  filter(PLATFORM == "Yes",
         PLATABRASION %in% c("No", "Yes")) |>
  group_by(STRAT_modn, RAWMATERIAL) |>
  mutate(total = n()) |>
  group_by(STRAT_modn, RAWMATERIAL, PLATABRASION, total) |>
  count() |>
  na.omit() |>
  summarize(prop = n/total) |>
  
  ggplot(aes(x = factor(STRAT_modn, ordered = T), y = prop,
             fill = factor(PLATABRASION)))+
  geom_bar(stat = "identity") +
  facet_wrap(~RAWMATERIAL) +
  
  labs(fill = "",
       x = "Cultural Phase",
       y = "Proportion") +
  theme_minimal()+
  theme_classic(base_size = 20)+
  scale_fill_manual(values = cols)+
  theme(axis.text.x = 
          element_text(angle = 45, hjust = 1)) -> plat_ab1



df.flakes |>
  filter(PLATFORM == "Yes",
         PLATABRASION %in% c("No", "Yes")) |>
  group_by(STRAT_mod, RAWMATERIAL) |>
  mutate(total = n()) |>
  group_by(STRAT_mod, RAWMATERIAL, PLATABRASION, total) |>
  count() |>
  na.omit() |>
  summarize(prop = n/total) |>
  
  ggplot(aes(x = factor(STRAT_mod, ordered = T), y = prop,
             fill = factor(PLATABRASION)))+
  geom_bar(stat = "identity") +
  facet_wrap(~RAWMATERIAL) +
  
  labs(fill = "",
       x = "Coastal-to-Terrestrial\nFoods",
       y = "Proportion") +
  theme_minimal()+
  theme_classic(base_size = 20)+
  scale_fill_manual(values = cols)+
  theme(axis.text.x = 
          element_text(angle = 45, hjust = 1),
        axis.title.x = element_text(vjust = 15)) -> plat_ab2
```

```{r}
png("../results/figures/fig8.png",width = 200, height = 220,
    units = "mm", res = 300)

ggarrange(
  plat_ab2, plat_ab1, nrow = 2,
  align = "h", labels = c("A", "B"),
  common.legend = TRUE
)

dev.off()
```

```{r Dirchlet_Prop_Ind00}
# Bayesian test
dir0 <- df.flakes |>
  filter(PLATFORM == "Yes",
         PLATABRASION %in% c("No", "Yes")) |>
  group_by(RAWMATERIAL, STRAT_mod) |>
  mutate(STRAT_mod = factor(STRAT_mod)) |>
  count() |>
  pivot_wider(names_from = RAWMATERIAL, values_from = n, values_fill = 0) |>
  mutate(total = Quartz + Quartzite + Silcrete,
         
         Quartz_prop = Quartz/total,
         Quartzite_prop = Quartzite/total,
         Silcrete_prop = Silcrete/total,
         
         y = cbind(Quartz_prop, Quartzite_prop, Silcrete_prop),
         )


my_prior <- 
  prior(normal(0,1), class = "Intercept") +
  prior(normal(0,1), class = "b", coef = "STRAT_mod25.5")+
  prior(normal(0,1), class = "b", coef = "STRAT_mod26.6")+
  prior(normal(0,1), class = "b", coef = "STRAT_mod27.2")+
  prior(normal(0,1), class = "b", coef = "STRAT_mod29.6")+
  prior(normal(0,1), class = "b", coef = "STRAT_mod37.1")+
  prior(normal(0,1), class = "b", coef = "STRAT_mod49.8")+
  
  prior(exponential(1), class = "phi")

bayes_beta0 <- brm(
  Quartz_prop ~ STRAT_mod,
  family = Beta(),
  data = dir0,
  prior = my_prior,
  iter = 4000,
  seed = 77600123,
  chains = 4,
  control = list(adapt_delta = 0.99, max_treedepth = 15),
  save_pars = save_pars(all = TRUE),
  cores = getOption("mc.cores", 14)
)


# create data with one row per group
newdata <- data.frame(STRAT_mod = levels(dir0$STRAT_mod))

# posterior predictions on response scale
post_preds <- posterior_epred(bayes_beta0, newdata = newdata)  # matrix: iterations x groups

# summary: posterior mean and 95% credible interval per group
summ <- apply(post_preds, 2, function(x) {
  c(mean = mean(x), quantile(x, c(0.025, 0.975)))
}) |>
  t() |> as_tibble()

summ$STRAT_mod <- levels(dir0$STRAT_mod)
summ


# Evaluate whether any group differenecs are significantly different
vars <- c(unique(summ$STRAT_mod))
pairwise_diffs <- combn(vars, 2, simplify = FALSE)

post_preds |>
  as_tibble() |>
  rename("8.4" = V1, "25.5" = V2, "26.6" = V3, "27.2" = V4,
         "29.6" = V5, "37.1" = V6, "49.8" = V7) |>
  mutate(
    !!!set_names(
      lapply(pairwise_diffs, \(pair) expr(!!sym(pair[1]) - !!sym(pair[2]))),
      sapply(pairwise_diffs, \(x) paste0("diff_", x[1], "_", x[2]))
    )
  ) |>
  select(`diff_8.4_25.5`:`diff_37.1_49.8`) |>
  pivot_longer(cols = `diff_8.4_25.5`:`diff_37.1_49.8`,
               values_to = "Delta", names_to = "Diffs") |>
  group_by(Diffs) |>
  summarize(Q_05 = quantile(Delta, 0.05),
            Q_95 = quantile(Delta, 0.95))
```

#### Cutting edge to mass

```{r}
df.flakes |>
  mutate(CE = ((TECHLENGTH*2)+TECHWIDTH)/(MASS)^(1/3)) |>
  ggplot(aes(x = factor(STRAT_modn, ordered = T), y = CE,
             fill = RAWMATERIAL,
             group = interaction(RAWMATERIAL, STRAT_modn)))+
  geom_boxplot()+
  geom_point(aes(color = "white"),
             position = position_jitterdodge(jitter.width = 0.1,
                                             jitter.height = 0,
                                             dodge.width = 0.75),
             alpha = 0.4) +
  
  labs(fill = "",
       x = "Cultural Phase",
       y = "Cutting Edge/\nMass") +
  theme_minimal()+
  theme_classic(base_size = 20)+
  scale_fill_manual(values = cols)+
  theme(axis.text.x = 
          element_text(angle = 20, hjust = 1)) +
  guides(color = "none")-> flake_trans1



df.flakes |>
  mutate(CE = ((TECHLENGTH*2)+TECHWIDTH)/(MASS)^(1/3)) |>
  ggplot(aes(x = factor(STRAT_mod, ordered = T), y = CE,
             fill = RAWMATERIAL,
             group = interaction(RAWMATERIAL, STRAT_mod)))+
  geom_boxplot()+
  geom_point(aes(color = "white"),
             position = position_jitterdodge(jitter.width = 0.1,
                                             jitter.height = 0,
                                             dodge.width = 0.75),
             alpha = 0.4) +
  
  labs(fill = "",
       x = "Coastal-to-Terrestrial\nFoods",
       y = "Cutting Edge/\nMass") +
  theme_minimal()+
  theme_classic(base_size = 20)+
  scale_fill_manual(values = cols)+
  theme(axis.text.x = 
          element_text(angle = 45, hjust = 1)) +
  guides(color = "none")-> flake_trans2

```

```{r}
png("../results/figures/fig9_1.png", width = 290, height = 120, units = "mm", res = 300)

ggarrange(
  flake_trans2,
  align = "h",
  common.legend = FALSE
)

dev.off()
```

```{r}

fit_df <- df.flakes |>
  mutate(RAWMATERIAL = droplevels(RAWMATERIAL)) |>
  group_by(RAWMATERIAL) |>
  mutate(CE = ((TECHLENGTH*2)+TECHWIDTH)/(MASS)^(1/3),
         STRAT_mod_s = as.numeric(scale(STRAT_mod, center = T, scale = T)),
         STRAT_mod = as.factor(STRAT_mod)) |>
  select(RAWMATERIAL, STRAT_mod, STRAT_mod_s, CE)

# Gamma prior
my_prior <- 
  prior(normal(0.5, 0.5), class = "Intercept")+
  prior(normal(1, 0.5), class = "b", coef = "RAWMATERIALQuartzite")+
  prior(normal(0, 1), class = "b", coef = "RAWMATERIALSilcrete")+
  
  prior(normal(1, 0.5), class = "b", coef = "STRAT_mod_s")+
  prior(normal(0.5, 1), class = "b", coef = "STRAT_mod_s:RAWMATERIALQuartzite")+
  prior(normal(0, 1), class = "b", coef = "STRAT_mod_s:RAWMATERIALSilcrete")+
  
  prior(gamma(2, 0.5), class = "shape")

fit_cuttingEdge <- brm(
  CE ~ STRAT_mod_s*RAWMATERIAL,
  data = fit_df,
  family = Gamma(link = "log"),
  prior = my_prior,
  cores = getOption("mc.cores", parallel::detectCores()),
  chains = 4,
  iter = 4000,
  seed = 2335078
)


my_prior <- 
  prior(normal(-0.5, 1), class = "Intercept")+
  
  prior(normal(0.5, 0.5), class = "b", coef = "STRAT_mod25.5")+
  prior(normal(0.5, 0.5), class = "b", coef = "STRAT_mod26.6")+
  prior(normal(0.5, 0.5), class = "b", coef = "STRAT_mod27.2")+
  prior(normal(0.5, 0.5), class = "b", coef = "STRAT_mod29.6")+
  prior(normal(1, 0.5), class = "b", coef = "STRAT_mod37.1")+
  prior(normal(1, 0.5), class = "b", coef = "STRAT_mod49.8")+
  
  prior(normal(1, 0.5), class = "b", coef = "RAWMATERIALQuartzite")+
  prior(normal(0.5, 0.5), class = "b", coef = "STRAT_mod25.5:RAWMATERIALQuartzite")+
  prior(normal(0.5, 0.5), class = "b", coef = "STRAT_mod26.6:RAWMATERIALQuartzite")+
  prior(normal(0.5, 0.5), class = "b", coef = "STRAT_mod27.2:RAWMATERIALQuartzite")+
  prior(normal(0.5, 1), class = "b", coef = "STRAT_mod29.6:RAWMATERIALQuartzite")+
  prior(normal(0.5, 1), class = "b", coef = "STRAT_mod37.1:RAWMATERIALQuartzite")+
  prior(normal(0.5, 1), class = "b", coef = "STRAT_mod49.8:RAWMATERIALQuartzite")+
  
  prior(normal(0, 1), class = "b", coef = "RAWMATERIALSilcrete")+
  prior(normal(0, 1), class = "b", coef = "STRAT_mod25.5:RAWMATERIALSilcrete")+
  prior(normal(0, 1), class = "b", coef = "STRAT_mod26.6:RAWMATERIALSilcrete")+
  prior(normal(0, 1), class = "b", coef = "STRAT_mod27.2:RAWMATERIALSilcrete")+
  prior(normal(0, 1), class = "b", coef = "STRAT_mod29.6:RAWMATERIALSilcrete")+
  prior(normal(1, 1), class = "b", coef = "STRAT_mod37.1:RAWMATERIALSilcrete")+
  prior(normal(1, 1), class = "b", coef = "STRAT_mod49.8:RAWMATERIALSilcrete")+
  
  prior(gamma(2, 0.5), class = "shape")

fit_cutting_phase <- brm(
  CE ~ STRAT_mod*RAWMATERIAL,
  data = fit_df,
  family = Gamma(link = "log"),
  prior = my_prior,
  cores = getOption("mc.cores", parallel::detectCores()),
  chains = 4,
  iter = 4000,
  seed = 23350787719387
)
```

```{r}
#| include: false
# Posterior checks for individual data

pp_check(fit_cuttingEdge, type = "dens_overlay_grouped",
         group = "STRAT_mod_s")
pp_check(fit_cuttingEdge, type = "stat_grouped", 
         group = "STRAT_mod_s")
pp_check(fit_cuttingEdge, type = "scatter_avg_grouped",
         group = "STRAT_mod_s")

pp_check(fit_cuttingEdge, type = "dens_overlay_grouped", 
         group = "RAWMATERIAL")
pp_check(fit_cuttingEdge, type = "stat_grouped", 
         group = "RAWMATERIAL")
pp_check(fit_cuttingEdge, type = "scatter_avg_grouped",
         group = "RAWMATERIAL")


pp_check(fit_cutting_phase, type = "dens_overlay_grouped",
         group = "STRAT_mod")
pp_check(fit_cutting_phase, type = "stat_grouped", 
         group = "STRAT_mod")
pp_check(fit_cutting_phase, type = "scatter_avg_grouped",
         group = "STRAT_mod")

pp_check(fit_cutting_phase, type = "dens_overlay_grouped", 
         group = "RAWMATERIAL")
pp_check(fit_cutting_phase, type = "stat_grouped", 
         group = "RAWMATERIAL")
pp_check(fit_cuttin_phase, type = "scatter_avg_grouped",
         group = "RAWMATERIAL")

loo1 <- loo(fit_cuttingEdge, moment_match = T)
plot(loo1)

loo2 <- loo(fit_cutting_phase, moment_match = T)
plot(loo2)


```

```{r}
new_data <- expand.grid(
  STRAT_mod_s = seq(min(fit_df$STRAT_mod_s),
                  max(fit_df$STRAT_mod_s), length.out = 100),
  RAWMATERIAL = unique(fit_df$RAWMATERIAL)
)


fit_df |>
  mutate(RAWMATERIAL = droplevels(RAWMATERIAL)) |>
  group_by(RAWMATERIAL) |>
  add_epred_draws(fit_cuttingEdge) |>
  median_qi(.epred, .width = 0.9) |>
  
  ggplot(aes(x = STRAT_mod_s, y = .epred,
             color = RAWMATERIAL, fill = RAWMATERIAL)) +
  geom_line(size = 1) +
  geom_ribbon(aes(ymin = .lower, ymax = .upper),
              alpha = 0.2, color = NA) +
  scale_fill_viridis_d() +
  scale_color_viridis_d() +
  scale_y_continuous("Posterior Median Cutting Edge/\nMass") +
  labs(x = "Terrestrial → Coastal Resource Use") +
  theme_classic(base_size = 18)+
  guides(fill = guide_legend(title = NULL),
         color = guide_legend(title = NULL)) -> CE_plot1



# Categorical cutting edge by cultural phase
ce <- conditional_effects(fit_cutting_phase, effects = "STRAT_mod:RAWMATERIAL", spaghetti = TRUE)
plot(ce, plot = FALSE)[[1]] +
    ggplot2::labs(x = "STRAT_modn (continuous)", y = "Cutting Edge (predicted)")

fit_cutting_phase |>
  epred_draws(
    newdata = distinct(fit_df, STRAT_mod, RAWMATERIAL)
    ) |>
  ggplot() +
  stat_halfeye(aes(x = STRAT_mod, y = .epred, fill = RAWMATERIAL),
               .width = c(.90, .5), scale = 0, linewidth = 1, point_size = 0.7,
               adjust = 0.8, width = 0.6,
               orientation = "vertical", point_interval = "median_qi")+
  facet_wrap(~RAWMATERIAL, scales = "free") +
  theme_minimal()+
  theme(legend.title = element_blank())+
  theme_classic(base_size = 18)+
  guides(color = "none")+
    theme(axis.text.x = 
          element_text(angle = 45, hjust = 1),
          text = element_text(size = 18),
          legend.position = "none") +
  ylab("Posterior Median Cutting Edge/\nMass") + xlab("Coastal-to-Terrestrial\nFoods") -> CE_plot2
    
post_comp |>
  pivot_longer(cols = Q_1_2:S_6_7, names_to = "Comparison", 
               values_to = "Post") |>
  group_by(Comparison) |>
  summarize(`Prob > 0` = mean(Post > 0))

# Test pairwise comparisons
pairs(emmeans(fit_cutting_phase, ~ STRAT_mod | RAWMATERIAL), level = 0.90, adjust = "tukey")

# Test hypothesis that slopes greater than 0
posterior <- as_draws(fit_cuttingEdge)$`1` # get posterior draws

mean(posterior$b_STRAT_mod_s > 0)
mean(posterior$`b_STRAT_mod_s:RAWMATERIALQuartzite` > 0)
mean(posterior$`b_STRAT_mod_s:RAWMATERIALSilcrete` > 0)
```

```{r}
png("../results/figures/fig9.png", width = 290, height = 220,
    units = "mm", res = 300)

ggarrange(
  CE_plot2, CE_plot1, nrow = 2,
  font.label = list(size = 25, face = "bold"),
  common.legend = FALSE, labels = c("A", "B"),
  widths = c(2, 1), heights = c(1.5, 1),
  label.y = c(1, 1.2),
  label.x = c(0.05, 0.05)
)

dev.off()
```

#### Flake elongation

```{r}
################### Flake elongation ######################
df.flakes |>
  ggplot(aes(x = factor(STRAT_mod, ordered = T), y = (TECHLENGTH/TECHWIDTH),
             fill = RAWMATERIAL,
             group = interaction(RAWMATERIAL, STRAT_mod)))+
  geom_boxplot()+
  geom_point(aes(color = "white"),
             position = position_jitterdodge(jitter.width = 0.1,
                                             jitter.height = 0, 
                                             dodge.width = 0.75),
             alpha = 0.4) +
  
  labs(fill = "",
       x = "Coastal-to-Terrestrial\nFoods",
       y = "Flake Elongation") +
  theme_minimal()+
  theme_classic(base_size = 18)+
  scale_fill_manual(values = cols)+
  theme(axis.text.x = 
          element_text(angle = 45, hjust = 1))+
  guides(color = "none") -> flake_elong2

```

```{r}
png("../results/figures/fig11.png", width = 290, height = 120,
    units = "mm", res = 300)

ggarrange(
  flake_elong2,
  align = "h",
  common.legend = FALSE
)

dev.off()
```

```{r}
# design model to look at the relationship between artifact mass and the 50th and 75th percentiles
# filter by values that caused errors in the models
fit_df <- df.flakes |>
  mutate(RAWMATERIAL = droplevels(RAWMATERIAL)) |>
  group_by(RAWMATERIAL) |>
  mutate(Elongation = (TECHLENGTH/TECHWIDTH),
         STRAT_mod_s = as.numeric(scale(STRAT_mod, center = T, scale = T)),
         STRAT_mod = as.factor(STRAT_mod)) |>
  select(RAWMATERIAL, STRAT_mod, STRAT_mod_s, Elongation)

# Gamma prior
my_prior <- 
  prior(normal(-0.5, 0.5), class = "Intercept")+
  prior(normal(0, 1), class = "b", coef = "RAWMATERIALQuartzite")+
  prior(normal(0, 1), class = "b", coef = "RAWMATERIALSilcrete")+
  
  prior(normal(-0.5, 0.5), class = "b", coef = "STRAT_mod_s")+
  prior(normal(0, 1), class = "b", coef = "STRAT_mod_s:RAWMATERIALQuartzite")+
  prior(normal(0, 1), class = "b", coef = "STRAT_mod_s:RAWMATERIALSilcrete")+
  
  prior(gamma(2, 0.5), class = "shape")

fit_Elong <- brm(
  Elongation ~ STRAT_mod_s*RAWMATERIAL,
  data = fit_df,
  family = Gamma(link = "log"),
  prior = my_prior,
  cores = getOption("mc.cores", parallel::detectCores()),
  chains = 4,
  iter = 4000,
  seed = 234506473)


my_prior <- 
  prior(normal(-0.5, 1), class = "Intercept")+
  
  prior(normal(0.5, 0.5), class = "b", coef = "STRAT_mod25.5")+
  prior(normal(0.5, 0.5), class = "b", coef = "STRAT_mod26.6")+
  prior(normal(0.5, 0.5), class = "b", coef = "STRAT_mod27.2")+
  prior(normal(0.5, 0.5), class = "b", coef = "STRAT_mod29.6")+
  prior(normal(1, 0.5), class = "b", coef = "STRAT_mod37.1")+
  prior(normal(1, 0.5), class = "b", coef = "STRAT_mod49.8")+
  
  prior(normal(1, 0.5), class = "b", coef = "RAWMATERIALQuartzite")+
  prior(normal(0.5, 0.5), class = "b", coef = "STRAT_mod25.5:RAWMATERIALQuartzite")+
  prior(normal(0.5, 0.5), class = "b", coef = "STRAT_mod26.6:RAWMATERIALQuartzite")+
  prior(normal(0.5, 0.5), class = "b", coef = "STRAT_mod27.2:RAWMATERIALQuartzite")+
  prior(normal(0.5, 1), class = "b", coef = "STRAT_mod29.6:RAWMATERIALQuartzite")+
  prior(normal(0.5, 1), class = "b", coef = "STRAT_mod37.1:RAWMATERIALQuartzite")+
  prior(normal(0.5, 1), class = "b", coef = "STRAT_mod49.8:RAWMATERIALQuartzite")+
  
  prior(normal(0, 1), class = "b", coef = "RAWMATERIALSilcrete")+
  prior(normal(0, 1), class = "b", coef = "STRAT_mod25.5:RAWMATERIALSilcrete")+
  prior(normal(0, 1), class = "b", coef = "STRAT_mod26.6:RAWMATERIALSilcrete")+
  prior(normal(0, 1), class = "b", coef = "STRAT_mod27.2:RAWMATERIALSilcrete")+
  prior(normal(0, 1), class = "b", coef = "STRAT_mod29.6:RAWMATERIALSilcrete")+
  prior(normal(1, 1), class = "b", coef = "STRAT_mod37.1:RAWMATERIALSilcrete")+
  prior(normal(1, 1), class = "b", coef = "STRAT_mod49.8:RAWMATERIALSilcrete")+
  
  prior(gamma(2, 0.5), class = "shape")

fit_Elong_phase <- brm(
  Elongation ~ STRAT_mod*RAWMATERIAL,
  data = fit_df,
  family = Gamma(link = "log"),
  prior = my_prior,
  cores = getOption("mc.cores", parallel::detectCores()),
  chains = 4,
  iter = 4000,
  seed = 29586854653857
)

```

```{r}
#| include: false
# Posterior checks for individual data

pp_check(fit_Elong, type = "dens_overlay_grouped",
         group = "STRAT_mod_s")
pp_check(fit_Elong, type = "stat_grouped", 
         group = "STRAT_mod_s")
pp_check(fit_Elong, type = "scatter_avg_grouped",
         group = "STRAT_mod_s")

pp_check(fit_Elong, type = "dens_overlay_grouped", 
         group = "RAWMATERIAL")
pp_check(fit_Elong, type = "stat_grouped", 
         group = "RAWMATERIAL")
pp_check(fit_Elong, type = "scatter_avg_grouped",
         group = "RAWMATERIAL")


pp_check(fit_Elong_phase, type = "dens_overlay_grouped",
         group = "STRAT_mod")
pp_check(fit_Elong_phase, type = "stat_grouped", 
         group = "STRAT_mod")
pp_check(fit_Elong_phase, type = "scatter_avg_grouped",
         group = "STRAT_mod")

pp_check(fit_Elong_phase, type = "dens_overlay_grouped", 
         group = "RAWMATERIAL")
pp_check(fit_Elong_phase, type = "stat_grouped", 
         group = "RAWMATERIAL")
pp_check(fit_Elong_phase, type = "scatter_avg_grouped",
         group = "RAWMATERIAL")

loo1 <- loo(fit_Elong, moment_match = T)
plot(loo1)

loo2 <- loo(fit_Elong_phase, moment_match = T)
plot(loo2)
```

```{r}

new_data <- expand.grid(
  STRAT_mod_s = seq(min(fit_df$STRAT_mod_s),
                  max(fit_df$STRAT_mod_s), length.out = 100),
  RAWMATERIAL = unique(fit_df$RAWMATERIAL)
)


epred_draws(fit_Elong, newdata = new_data) |>
  median_qi(.epred, .width = 0.9) |>
  
  ggplot(aes(x = STRAT_mod_s, y = .epred,
             color = RAWMATERIAL, fill = RAWMATERIAL)) +
  geom_line(size = 1) +
  geom_ribbon(aes(ymin = .lower, ymax = .upper),
              alpha = 0.2, color = NA) +
  scale_fill_viridis_d() +
  scale_color_viridis_d() +
  scale_y_continuous("") +
  labs(x = "Fish → Non-fish (Standardized)") +
  theme(legend.title = "") +
  theme_classic(base_size = 18) -> Elong1

post <- as_draws_df(fit_Elong) |>
  mutate(Quartzite = b_STRAT_mod_s +
           `b_STRAT_mod_s:RAWMATERIALQuartzite`,
         Silcrete = b_STRAT_mod_s +
           `b_STRAT_mod_s:RAWMATERIALSilcrete`,
         Quartz = b_STRAT_mod_s) |>
  pivot_longer(Quartzite:Quartz,
               values_to = "Slope", names_to = "Rawmaterial") |>
  select(Slope, Rawmaterial) |>
  group_by(Rawmaterial) |>
  summarize(`Prob(>0)` = mean(Slope > 0))

post




fit_Elong_phase |>
  epred_draws(
    newdata = distinct(fit_df, STRAT_mod, RAWMATERIAL)
    ) |>
  ggplot() +
  stat_halfeye(aes(x = STRAT_mod, y = .epred, fill = RAWMATERIAL),
               .width = c(.90, .5), scale = 0, linewidth = 1, point_size = 0.7,
               adjust = 0.8, width = 0.6,
               orientation = "vertical", point_interval = "median_qi")+
  facet_wrap(~RAWMATERIAL, scales = "free") +
  theme_minimal()+
  theme(legend.title = element_blank())+
  theme_classic(base_size = 18)+
  guides(color = "none")+
    theme(axis.text.x = 
          element_text(angle = 45, hjust = 1),
          text = element_text(size = 18),
          legend.position = "none") +
  ylab("Posterior Median Flake Elongation") + 
  xlab("Coastal-to-Terrestrial\nFoods") -> Elong_plot2

# Pairwise comparisons
pairs(emmeans(fit_Elong_phase, ~ STRAT_mod | RAWMATERIAL), 
      level = 0.90, adjust = "tukey")
```

```{r}
png("../results/figures/fig12.png", width = 290, height = 220,
    units = "mm", res = 300)

ggarrange(
  Elong_plot2, Elong_plot1, nrow = 2,
  font.label = list(size = 25, face = "bold"),
  common.legend = FALSE, labels = c("A", "B"),
  widths = c(2, 1), heights = c(1.5, 1),
  label.y = c(1, 1.23),
  label.x = c(0.03, 0.03)
)

dev.off()
```

### Flake Utility to Reduction Intensity

```{r}
lm_red <- df.flakes |>
  # filter by outliers and variables with < 10 observations
  filter(Utility_small < 2500,
         Utility_small > 0) |>
  
  select(Reduction, Utility_small,
         STRAT_mod)


lm_red$STRAT_mod_s <- scale(lm_red$STRAT_mod, center = T, scale = T)

Bayes_ut1 <- lm_red |>
  mutate(Utility_s = Utility_small /100,
         Reduction_s = as.numeric(scale(Reduction, scale = T, center = T)),
         STRAT_mod = factor(STRAT_mod))
```

```{r}

# Run Bayesian model with varying slopes
bayes_poly0 <- brm(Utility_s ~ 1 + poly(Reduction_s, 2, raw = TRUE),
              data = Bayes_ut1,
              family = Gamma(link = "log"),
              iter = 2000,
              chains = 2,
              seed = 112,
              control = list(adapt_delta = 0.95),
              #prior=my_prior,
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))

bayes_poly00 <- brm(Utility_s ~ 1 + poly(Reduction_s, 2, raw = TRUE) + 
                      (0 + poly(Reduction_s, 2, raw = TRUE) | STRAT_mod/RAWMATERIAL),
              data = Bayes_ut1,
              family = Gamma(link = "log"),
              iter = 2000,
              chains = 2,
              seed = 1122,
              control = list(adapt_delta = 0.95),
              #prior=my_prior,
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))

bayes_poly000 <- brm(Utility_s ~ 1 + RAWMATERIAL + poly(Reduction_s, 2, raw = TRUE) + 
                      (0 + poly(Reduction_s, 2, raw = TRUE) | STRAT_mod),
              data = Bayes_ut1,
              family = Gamma(link = "log"),
              iter = 2000,
              chains = 2,
              seed = 11223,
              control = list(adapt_delta = 0.95),
              #prior=my_prior,
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))

Okbayes_poly1 <- brm(Utility_s ~ 1 + poly(Reduction_s, 2, raw = TRUE) + 
                       RAWMATERIAL,
              data = Bayes_ut1,
              family = Gamma(link = "log"),
              iter = 2000,
              chains = 2,
              seed = 113,
              control = list(adapt_delta = 0.95),
              #prior=my_prior,
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))

bayes_poly2 <- brm(Utility_s ~ 1 + poly(Reduction_s, 2, raw = TRUE) + 
                     RAWMATERIAL + STRAT_mod_s,
              data = Bayes_ut1,
              family = Gamma(link = "log"),
              iter = 2000,
              chains = 2,
              seed = 114,
              control = list(adapt_delta = 0.95),
              #prior=my_prior,
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))

bayes_poly22 <- brm(Utility_s ~ 1 + poly(Reduction_s, 2, raw = TRUE) + 
                      RAWMATERIAL + STRAT_mod,
              data = Bayes_ut1,
              family = Gamma(link = "log"),
              iter = 2000,
              chains = 2,
              seed = 1144,
              control = list(adapt_delta = 0.95),
              #prior=my_prior,
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))

bayes_poly23 <- brm(Utility_s ~ 1 + poly(Reduction_s, 2, raw = TRUE) + 
                      (0+poly(Reduction_s, 2, raw = TRUE)|RAWMATERIAL) + STRAT_mod_s,
              data = Bayes_ut1,
              family = Gamma(link = "log"),
              iter = 2000,
              chains = 2,
              seed = 1144,
              control = list(adapt_delta = 0.95),
              #prior=my_prior,
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))


bayes_poly3 <- brm(Utility_s ~ 1 + STRAT_mod_s + poly(Reduction_s, 2, raw = TRUE) +
                   (0 + poly(Reduction_s, 2, raw = TRUE) | RAWMATERIAL),
              data = Bayes_ut1,
              family = Gamma(link = "log"),
              iter = 2000,
              chains = 2,
              seed = 115,
              control = list(adapt_delta = 0.95),
              #prior=my_prior,
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))

bayes_poly4 <- brm(Utility_s ~ 1 + STRAT_mod_s + poly(Reduction_s, 2, raw = TRUE) +
                   (0 + poly(Reduction_s, 2, raw = TRUE) | RAWMATERIAL),
              data = Bayes_ut1,
              family = Gamma(link = "log"),
              iter = 2000,
              chains = 2,
              seed = 116,
              control = list(adapt_delta = 0.95),
              #prior=my_prior,
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))


bayes_poly5 <- brm(Utility_s ~ 1 + poly(Reduction_s, 2, raw = TRUE) +
                   (0 + poly(Reduction_s, 2, raw = TRUE) | STRAT_mod/RAWMATERIAL),
              data = Bayes_ut1,
              family = Gamma(link = "log"),
              iter = 2000,
              chains = 2,
              seed = 117,
              control = list(adapt_delta = 0.95),
              #prior=my_prior,
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))





```

```{r}
#| include: false

# Validate model with posterior checks

loo0 <- loo(bayes_poly0)
loo00 <- loo(bayes_poly00)
loo000 <- loo(bayes_poly000)

loo1 <- loo(Okbayes_poly1)
loo2 <- loo(bayes_poly2)
loo22 <- loo(bayes_poly22)
loo23 <- loo(bayes_poly23)

loo3 <- loo(bayes_poly3)
loo4 <- loo(bayes_poly4)
loo5 <- loo(bayes_poly5)

loo_compare(loo0, loo00, loo000, loo1, loo2, loo22, loo3, loo4, loo5)


pp_check(bayes_poly000, type = "dens_overlay")
pp_check(bayes_poly000, type = "stat")
pp_check(bayes_poly000, type = "scatter_avg_grouped", group = "RAWMATERIAL")
pp_check(bayes_poly000, type = "scatter_avg_grouped", group = "STRAT_mod")
```

```{r}
# Gamma prior
my_prior <-

  # Intercept
  prior(normal(1, 1), class = Intercept)+
  
  prior(normal(0.5, 1), class = b, coef = "RAWMATERIALQuartzite")+
  prior(normal(0, 1), class = b, coef = "RAWMATERIALSilcrete")+
  
  # Polynomial factor 1
  prior(normal(0.5, 1), class = b, coef = "polyReduction_s2rawEQTRUE1")+

  # Polynomial factor 2
  prior(normal(0.5, 1), class = b, coef = "polyReduction_s2rawEQTRUE2")+
  
  prior(exponential(1), class = sd)+

  # Gamma shape
  prior(exponential(1), class = shape)

Bayes_ut1 <- Bayes_ut1[-c(73, 306, 636),]

bayes_poly_raw <- brm(Utility_s ~ 1 + RAWMATERIAL + poly(Reduction_s, 2, raw = TRUE) + 
                      (0 + poly(Reduction_s, 2, raw = TRUE) | STRAT_mod),
              data = Bayes_ut1,
              family = Gamma(link = "log"),
              iter = 4000,
              chains = 1,
              seed = 112233,
              control = list(adapt_delta = 0.95, max_treedepth = 15),
              prior=my_prior,
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))

loo_raw <- loo(bayes_poly_raw, moment_match = TRUE)
which(loo_raw$diagnostics$pareto_k>0.7)

pp_check(bayes_poly_raw, type = "dens_overlay")
pp_check(bayes_poly_raw, type = "stat")
pp_check(bayes_poly_raw, type = "stat_grouped", group = "RAWMATERIAL")
pp_check(bayes_poly_raw, type = "scatter_avg_grouped", group = "RAWMATERIAL")
pp_check(bayes_poly_raw, type = "scatter_avg_grouped", group = "STRAT_mod")
```

```{r}
fit_df <- Bayes_ut1
x_seq <- seq(min(fit_df$Reduction_s, na.rm = TRUE),
             max(fit_df$Reduction_s, na.rm = TRUE),
             length.out = 100)

draws <- as_draws_df(bayes_poly000)

# All combinations of grouping levels
slope_draws <- expand_grid(
  draws,
  Reduction_s = x_seq,
  STRAT_mod = unique(fit_df$STRAT_mod)
) |>
  mutate(
    eta = b_Intercept +
          b_polyReduction_s2rawEQTRUE1 * Reduction_s +
          b_polyReduction_s2rawEQTRUE2 * Reduction_s^2,

    slope = exp(eta) *
            (b_polyReduction_s2rawEQTRUE1 +
             2 * b_polyReduction_s2rawEQTRUE2 * Reduction_s)
  )


slope_summary <- slope_draws |>
  group_by(Reduction_s) |>
  summarise(
    mean = mean(slope),
    lwr = quantile(slope, 0.05),
    upr = quantile(slope, 0.95),
    .groups = "drop"
  )


ggplot(slope_summary, aes(Reduction_s, mean)) +
  geom_line(linewidth = 1) +
  geom_ribbon(aes(ymin = lwr, ymax = upr),
              alpha = 0.25) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  labs(
    x = "Reduction (Scaled)",
    y = expression(Delta~"Utility-to-Reduction"),
  ) +
  theme_minimal()
```

```{r}
x_seq <- seq(min(fit_df$Reduction_s, na.rm = TRUE),
             max(fit_df$Reduction_s, na.rm = TRUE),
             length.out = 100)

draws <- as_draws_df(bayes_poly000)
ranef <- ranef(bayes_poly000)$`STRAT_mod`[,,]


groups_to_plot <- fit_df |>
  count(STRAT_mod) |>
  rename("group" = "STRAT_mod") |>
  arrange(desc(n)) |>
  pull(group)



slope_group_draws <- map_dfr(groups_to_plot, function(g) {

  
  g1 <- paste0("r_STRAT_mod[", g, ",polyReduction_s2rawEQTRUE1]")
  g2 <- paste0("r_STRAT_mod[", g, ",polyReduction_s2rawEQTRUE2]")

  expand_grid(
    draws,
    Reduction_s = x_seq
  ) |>
    mutate(
      group = g,

      b1g = b_polyReduction_s2rawEQTRUE1 + .data[[g1]],
      b2g = b_polyReduction_s2rawEQTRUE2 + .data[[g2]],

      eta = b_Intercept +
            b1g * Reduction_s +
            b2g * Reduction_s^2,

      slope = exp(eta) * (b1g + 2 * b2g * Reduction_s)
    )
})


slope_group_summary <- slope_group_draws |>
  group_by(group, Reduction_s) |>
  summarise(
    mean = mean(slope),
    lwr = quantile(slope, 0.05),
    upr = quantile(slope, 0.95),
    .groups = "drop"
  )

ggplot(slope_group_summary,
       aes(Reduction_s, mean, color = group)) +
  geom_line(linewidth = 1) +
  geom_ribbon(aes(ymin = lwr, ymax = upr, fill = group),
              alpha = 0.25) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  #facet_wrap(~ group, scales = "free_y") +
  labs(
    x = "Reduction (Scaled)",
    y = expression(Delta~"Utility-to-Reduction"),
    color = "Ratio"
  ) +
  theme_minimal()+
  guides(fill = "none")

```

```{r}
# Probability slopes are greater than 0
positive_prob <- slope_group_draws |>
  group_by(group, Reduction_s) |>
  summarise(
    Pr_positive = mean(slope > 0),
    .groups = "drop"
  ) |> 
  
  filter(Pr_positive > 0.89) |>
  group_by(group) |>
  summarize(max = max(Reduction_s))

positive_prob

# Expected slope for each strat at specified reduction value
em_slopes_resp <- emtrends(
  bayes_poly000,
  ~ STRAT_mod,
  var = "Reduction_s",
  # Compute from the minimum significant slope for all strats
  at = list(Reduction_s = c(min(positive_prob$max))),
  type = "response",
  allow_new_levels = TRUE,
  re_formula = NULL
)
plot(em_slopes_resp)+
  xlab(expression(Delta*"Utility-to-Reduction"))+
  ylab("Ratio")
pairs(em_slopes_resp)


# Expected Utility for each strat at specified reduction value
em_slopes_resp <- emmeans(
  bayes_poly000,
  ~ STRAT_mod,
  var = "Reduction_s",
  # Compute from the minimum significant slope for all strats
  at = list(Reduction_s = c(min(positive_prob$max))),
  type = "response",
  allow_new_levels = TRUE,
  re_formula = NULL
)
plot(em_slopes_resp)+xlab("why?")
pairs(em_slopes_resp)

```
