---
title: "SBF_Cores"
format: html
editor: visual
---

```{r libraries}
#| warning: false
#| message: false

# To plot figures

library(ggplot2)
library(forcats)
library(ggpubr)
library(ggridges)
library(cowplot)
library(ggforce)

library(infer)
#library(rcompanion)
library(purrr)
library(modelr)
#library(rcompanion)
library(viridis)

library(scales)
library(stringr)

# To generate tables
library(gtsummary)
library(gt)
library(broom)
library(broom.mixed)

library(stargazer)
library(kableExtra)

# To tidy the data
library(tidyr)
library(tidyverse)
library(dplyr)
library(forcats)
library(tidybayes)

# Bayesian models
library(brms)
library(emmeans)
library(loo)
library(BayesFactor)
library(posterior)
```

```{r ReadData}
#| message: false
#| warning: false

# Read and clean data
df_sum24 <- read.csv("../data/AG_Summer2024_SBF_Final.csv") |>
  select(-c('X')) |>
  filter(RAWMATERIAL != "BWA UPPER 1" &
           RAWMATERIAL %in% c("Quartz", "Quartzite", "Silcrete")) |>
  mutate(#STRAT = ifelse(STRAT == "3a", "3", # combine strat 3a and 3b
          #              ifelse(STRAT == "3b", "3", STRAT)),
         STRAT_mod = ifelse(STRAT %in% c("5"), "Terrestrial",
                     ifelse(STRAT %in% c("4a", "4b"), "Mixed", "Coastal"))) |>
  mutate(STRAT = factor(STRAT),
         STRAT_mod = factor(STRAT_mod))

df_sum25 <- read.csv("../data/AG_Summer2025_SBF_Final.csv") |>
  filter(RAWMATERIAL != "BWA UPPER 1" &
           RAWMATERIAL %in% c("Quartz", "Quartzite", "Silcrete")) |>
  mutate(#STRAT = ifelse(STRAT == "3a", "3", # combine strat 3a and 3b
          #              ifelse(STRAT == "3b", "3", STRAT)),
         STRAT_mod = ifelse(STRAT %in% c("5"),"Terrestrial",
                     ifelse(STRAT %in% c("4a", "4b"), "Mixed", "Coastal"))) |>
  mutate(STRAT = factor(STRAT),
         STRAT_mod = factor(STRAT_mod)) |>
  
  select(-c(X))

# student's dataframe
df_One <- read_csv("../data/DataSheet_1.csv")|>
  mutate(STRAT = tolower(Layer),
         
         PLATFORMWIDTH = parse_number("Platform Width"),
         PLATFORMTHICKNESS = parse_number("Platform Thickness"),
         MAXLENGTH = parse_number("Maximum Length"),
         TECHLENGTH = parse_number("Technological Length"),
         MAXWIDTH = parse_number("Maximum Width"),
         TECHWIDTH = parse_number("Technological Width"),
         MAXTHICKNESS = parse_number("Thickness"),
         MASS = parse_number("Mass"))

df_One <- df_One[1:289,]

df_One_flakes <- df_One |>
  
  add_column(OTHERUNIT = NA, .before = "Raw Material") |>

  rename(SITE = Site, UNIT = Unit, NAMED_ID = `Other Name`,
         RAWMATERIAL = `Raw Material`, CORTEX = `Cortex Percent`,
         CORTEXTYPE = `Cortex Origin`, ARTIFACTCLASS = `Artifact class`,
         COMPLETENESS = Complete, PLATFORM = `Platform?`,
         FLAKEINITIATION = Initiated, FLAKETERMINATION = Termination,
         FLAKEGEOMETRY = `Flake Geometry`, PLATFORMPREP = `Platform Preparation`,
         PLATABRASION = PlatformAbrasion, 
         STAGE = `Flaking Stage`) |>
  
  select(-c(Layer, Notes, Photo,
            `Platform Width`:`Platform Thickness`, `Maximum Length`:Mass)) |>
  
  mutate(#STRAT = ifelse(STRAT == "3a", "3", # combine strat 3a and 3b
          #            ifelse(STRAT == "3b", "3", 
           #                  ifelse(STRAT == "5a", "5", STRAT))),
         STRAT_mod = ifelse(STRAT %in% c("5"),"Terrestrial",
                     ifelse(STRAT %in% c("4a", "4b"), "Mixed", "Coastal"))) |>
  mutate(STRAT = factor(STRAT),
         STRAT_mod = factor(STRAT_mod)) |>
  
  relocate(STRAT, .before = "UNIT") |>
  relocate(CORTEXTYPE, .before = "ARTIFACTCLASS")
  
  

# student's Dataframe
df_Two <- read_csv("../data/DataSheet_2.csv") |>
  
  rename(SITE = Site, STRAT = Layer, UNIT = Unit, NAMED_ID = `Other Name`,
         RAWMATERIAL = `Raw Material`, CORTEX = `Cortex Percent`,
         ARTIFACTCLASS = `Artifact class`, CORTEXTYPE = `Cortex Origin`,
         COMPLETENESS = Complete, PLATFORM = `Platform?`,
         FLAKEINITIATION = Initiated, FLAKETERMINATION = Termination,
         FLAKEGEOMETRY = `Flake Geometry`, PLATFORMPREP = `Platform Preparation`,
         PLATABRASION = `PlatformAbrasion`, PLATFORMWIDTH = `Platform Width`,
         PLATFORMTHICKNESS = `Platform Thickness`, STAGE = `Flaking Stage`,
         MAXLENGTH = `Maximum Length`, TECHLENGTH = `Technological Length`,
         MAXWIDTH = `Maximum Width`, TECHWIDTH = `Technological Width`,
         MAXTHICKNESS = Thickness, MASS = Mass) |>
  
  select(-c(`...2`,Notes:Photo))

df_Two_flakes <- df_Two |>
  
  add_column(OTHERUNIT = NA, .before = "RAWMATERIAL") |>
  
  mutate(#STRAT = ifelse(STRAT == "3a", "3", # combine strat 3a and 3b
          #          ifelse(STRAT == "3b", "3", 
           #                ifelse(STRAT == "5a", "5", STRAT))),
          STRAT_mod = ifelse(STRAT %in% c("5"),"Terrestrial",
                     ifelse(STRAT %in% c("4a", "4b"), "Mixed", "Coastal"))) |>
  mutate(STRAT = factor(STRAT),
         STRAT_mod = factor(STRAT_mod))




df_Two_flakes <- df_Two_flakes[1:421,] |>
  relocate(CORTEXTYPE, .before = "ARTIFACTCLASS")
  

df_students <- rbind(df_Two_flakes, df_One_flakes)


df <- rbind(df_sum24, df_sum25) |>
  merge(df_students, all = T) |>
  mutate(TECHLENGTH = as.numeric(TECHLENGTH),
         MAXWIDTH = as.numeric(MAXWIDTH),
         MAXTHICKNESS = as.numeric(MAXTHICKNESS)) |>
  filter(STRAT %in% c("1", "2", "3a", "3b", "3", "4a", "4b", "5")) |>
  
  mutate(ARTIFACTCLASS = ifelse(ARTIFACTCLASS == "flake", "Flake",
                         ifelse(ARTIFACTCLASS == "blade", "Flake",
                         ifelse(ARTIFACTCLASS == "Flake/Blade", "Flake",
                         ifelse(ARTIFACTCLASS == "Fragment", "Flake",
                                                     ARTIFACTCLASS)))),
         
         RAWMATERIAL = as.factor(
           ifelse(RAWMATERIAL == "Silcrete flake", "Silcrete",
                              ifelse(RAWMATERIAL == "OTHER", "Other",
                                     RAWMATERIAL))),
         
         CORTEX = ifelse(CORTEX == "10-40%", "11-40%",
                  ifelse(CORTEX == "90-99%", "91-99%",
                  ifelse(CORTEX == "60-90%", "61-90%",
                  ifelse(CORTEX == "40-60%", "41-60%",
                         CORTEX)))),
         
         STRAT_mod = ifelse(STRAT == "1", 27.2,
                     ifelse(STRAT == "2", 37.1,
                     ifelse(STRAT == "3a", 49.8,
                     ifelse(STRAT == "3b", 29.6,
                     ifelse(STRAT == "4a", 26.6,
                     ifelse(STRAT == "4b", 25.5,
                     ifelse(STRAT == "5", 8.4, 0))))))),
         
         STRAT_modn = ifelse(STRAT %in% c("5"),"Pre-Megamidden",
                     ifelse(STRAT %in% c("4a", "4b"), "Transitional", 
                            "Megamidden")),
         STRAT_modn = fct_relevel(STRAT_modn, 
                                  c("Pre-Megamidden", "Transitional",
                                    "Megamidden"))) |>
  
  filter(RAWMATERIAL %in% c("Quartz", "Quartzite", "Silcrete"),
         CORTEX != "\\",
         MAXWIDTH < 1250,
         MASS < 300)


# take average core flake scar length
df |>
  dplyr::filter(ARTIFACTCLASS=="Core") |>
  group_by(RAWMATERIAL, STRAT) |>
  summarize(Ave_FlakeLength = mean(LENGHTLONGESTFLAKESCAR)) -> core_size


# set values for small, medium, and large slug effect sizes
small <- 5.18



# Subset data by flakes and flake variables
core_bind <- full_join(core_size, df) |>
  filter(ARTIFACTCLASS == "Flake" & COMPLETENESS == "Complete") |>
  group_by(RAWMATERIAL, STRAT) |>
  mutate(Utility_small = TECHLENGTH*(TECHLENGTH - small),
         
         Transport_small = Utility_small/((MAXTHICKNESS/TECHLENGTH)*TECHLENGTH^3),
         
         Reduction = TECHLENGTH/Ave_FlakeLength) |>
  
  select(any_of(names(df_students)), c(Utility_small:Reduction), STRAT_mod, STRAT_modn) -> df.flakes

# Subset data by cores and core variables
df_cores <- df |>
  filter(ARTIFACTCLASS == "Core" & CORECOMPLETENESS == "Complete") |>
  mutate(SA_Ellipse = (4*pi)*
           ((((((MAXLENGTH/2)*(MAXWIDTH/2))^1.6075)+
           (((MAXLENGTH/2)*(MAXTHICKNESS/2))^1.6075)+
           (((MAXWIDTH/2)+(MAXTHICKNESS/2))^1.6075))/3)^(1/1.6075)))

# Subset data by retouch and retouch variables
df_retouch <- df |>
  filter(ARTIFACTCLASS == "RetouchedTool" & RAWMATERIAL != "BWA UPPER 1" &
           COMPLETENESS == "Complete") |>
  mutate(Utility_small = TECHLENGTH*(TECHLENGTH - small),
         
         Transport_small = Utility_small/((MAXTHICKNESS/TECHLENGTH)*TECHLENGTH^3)) |>
  select(1:11,21:27,29:60, Utility_small:Transport_small)

# Read tabulated data from previous publications (i.e. Jerardino & Yates)
sbf_df <- read.csv("../data/SBF_ToolType.csv")
sbf_un <- read.csv("../data/SBF_ToolType_unmod.csv")

```

## Core Descriptions

```{r}
#| warning: false
#| message: false
########################## Conard typology #############################
df_cores |>
  group_by(STRAT_mod, RAWMATERIAL) |>
  mutate(total = n()) |>
  group_by(STRAT_mod, RAWMATERIAL, CONARDUNIFIEDTYPE, total) |>
  count() |>
  summarize(prop = n/total) |>
  
  ggplot(aes(x = factor(STRAT_mod, ordered = TRUE), y = prop, fill = factor(CONARDUNIFIEDTYPE)))+
  geom_bar(stat = "identity") +
  facet_wrap(~RAWMATERIAL) +
  
  labs(fill = "",
       x = "Layers",
       y = "Proportion") +
  theme_minimal()+
  theme_classic(base_size = 20)+
  scale_fill_viridis_d()+
  theme(axis.text.x = 
          element_text(angle = 45, hjust = 1)) -> core_conard


png("../results/figures/Figure9.png", width = 290, height = 120,
    units = "mm", res = 300)

  ggarrange(
  core_conard,
  font.label = list(size = 25, face = "bold"),
  widths = c(2, 1), heights = c(1.5, 1),
  label.y = c(1, 1.2),
  label.x = c(0.05, 0.05)
  )

dev.off()
```

###### Core Type Bayesian Test

```{r}
fit_df <- df_cores |>
  mutate(STRAT_mod = as.factor(STRAT_mod))


my_prior <- c(
  prior(normal(15, 5), class = "Intercept", dpar = "muInclined"),
  prior(normal(70, 15), class = "Intercept", dpar = "muPlatform")
)

bayes_cat <- brm(CONARDUNIFIEDTYPE ~ 1 + (1 | STRAT_mod/RAWMATERIAL),
                 family = categorical(),
                 data = fit_df,
                  prior = my_prior,
                  iter = 4000,
                  seed = 1234,
                  chains = 4,
                  control = list(adapt_delta = 0.99),
                  save_pars = save_pars(all = TRUE),
                  cores = getOption("mc.cores", parallel::detectCores())
)


newdat <- expand.grid(
  STRAT_mod = unique(fit_df$STRAT_mod),
  RAWMATERIAL = unique(fit_df$RAWMATERIAL)
)

props <- bayes_cat |>
  epred_draws(
    newdata = newdat,
    allow_new_levels = TRUE,
    re_formula = NULL   # include strat-level random effects
  ) |>
  group_by(STRAT_mod, RAWMATERIAL, .category) |>
  summarise(
    mean = mean(.epred),
    l95  = quantile(.epred, 0.05),
    u95  = quantile(.epred, 0.95),
    .groups = "drop"
  ) |>
  rename("CONARDUNIFIEDTYPOLOGY" = .category)


```

```{r}
# posterior comparison
pp <- fit_df |>
  add_epred_draws(bayes_cat, ndraws = 500) |> 
  group_by(.draw, STRAT_mod, RAWMATERIAL, .category) |>
  summarise(prob = mean(.epred), .groups = "drop")

pp |>
  filter(.category == "Bipolar") |>
  pivot_wider(
    names_from = c(STRAT_mod),
    values_from = prob
  ) |>
  na.omit() |>
  mutate(
    diff1 = `8.4` - `26.6`,
    diff2 = `8.4` - `27.2`,
    diff3 = `8.4` - `25.5`,
    diff4 = `8.4` - `29.6`,
    diff5 = `8.4` - `37.1`,
    diff6 = `8.4` - `49.8`,
    
    diff7 = `26.6` - `27.2`,
    diff8 = `26.6` - `25.5`,
    diff9 = `26.6` - `29.6`,
    diff10 = `26.6` - `37.1`,
    diff11 = `26.6` - `49.8`,
    
    diff12 = `27.2` - `25.5`,
    diff13 = `27.2` - `29.6`,
    diff14 = `27.2` - `37.1`,
    diff15 = `27.2` - `49.8`,
    
    diff16 = `25.5` - `29.6`,
    diff17 = `25.5` - `37.1`,
    diff18 = `25.5` - `49.8`,
    
    diff19 = `29.6` - `37.1`,
    diff20 = `29.6` - `49.8`,
    
    diff21 = `37.1` - `49.8`
    
  ) |>
  summarise(across(diff1:diff21, list(mean = mean, 
                                      lwr = ~quantile(.x,probs = 0.05),
                                      upr = ~quantile(.x,probs = 0.95)))) |>
  
  matrix(ncol = 3, nrow = 21, byrow = TRUE) |>
  as_tibble() |>
  rename("mu" = "V1", "lwr" = "V2", "upr" = "V3") |>
  mutate(mu = as.numeric(mu),
         lwr = as.numeric(lwr),
         upr = as.numeric(upr)) 
```

#### Discrete

```{r}
fit_df <- df_cores |>
  mutate(CE = SCARCOUNT/SA_Ellipse,
         STRAT_mod_s = as.numeric(scale(STRAT_mod, center=T, scale = T)))

CE_prior <- 
  prior(normal(0, 0.5), class = "Intercept")+
  prior(normal(1, 0.5), class = "b", 
        coef = "RAWMATERIALQuartzite")+
  prior(normal(0, 1), class = "b", coef = "STRAT_mod_s")+
  prior(normal(1, 0.5), class = "b", 
        coef = "STRAT_mod_s:RAWMATERIALSilcrete")+
  
  prior(gamma(2, 0.5), class = "shape")



fit_CE <- brm(CE ~ STRAT_mod_s*RAWMATERIAL,
               data = fit_df,
  family = Gamma(link = "log"),
  prior = CE_prior,
  cores = getOption("mc.cores", parallel::detectCores()),
  chains = 2,
  iter = 4000,
  seed = 12345
)

```

```{r}
#| include: false

# Posterior checks for individual data

pp_check(fit_CE, type = "dens_overlay",
         group = "STRAT_mod_s")
pp_check(fit_CE, type = "stat", 
         group = "STRAT_mod_s")
pp_check(fit_CE, type = "scatter_avg",
         group = "STRAT_mod_s")

pp_check(fit_CE, type = "dens_overlay_grouped", 
         group = "RAWMATERIAL")
pp_check(fit_CE, type = "stat_grouped", 
         group = "RAWMATERIAL")
pp_check(fit_CE, type = "scatter_avg_grouped",
         group = "RAWMATERIAL")

loo1 <- loo(fit_CE, moment_match = T)
plot(loo1)
```

```{r}
fit_df <- fit_df |>
  mutate(RAWMATERIAL = droplevels(RAWMATERIAL))
new_data <- expand.grid(
  STRAT_mod_s = seq(min(fit_df$STRAT_mod_s),
                  max(fit_df$STRAT_mod_s), length.out = 100),
  RAWMATERIAL = unique(fit_df$RAWMATERIAL)
)


epred_draws(fit_CE, newdata = new_data,
            allow_new_levels = TRUE) |>
  median_qi(.epred, .width = 0.9) |>
  
  ggplot(aes(x = STRAT_mod_s, y = .epred,
             color = RAWMATERIAL, fill = RAWMATERIAL)) +
  geom_line(size = 1) +
  geom_ribbon(aes(ymin = .lower, ymax = .upper),
              alpha = 0.2, color = NA) +
  scale_fill_viridis_d() +
  scale_color_viridis_d() +
  scale_y_continuous("") +
  labs(x = "Terrestrial → Coastal Resource Use") +
  theme(legend.title = "") +
  theme_classic(base_size = 18) -> plot_CE1

```

```{r}
post <- as_draws_df(fit_CE) |>
  mutate(Quartzite = b_STRAT_mod_s +
           `b_STRAT_mod_s:RAWMATERIALQuartzite`,
         Silcrete = b_STRAT_mod_s +
           `b_STRAT_mod_s:RAWMATERIALSilcrete`,
         Quartz = b_STRAT_mod_s) |>
  pivot_longer(Quartzite:Quartz,
               values_to = "Slope", names_to = "Rawmaterial") |>
  select(Slope, Rawmaterial) |>
  group_by(Rawmaterial) |>
  summarize(`Prob(>0)` = mean(Slope > 0))

post
```

```{r}

fit_CE_anova <- brm(CE ~ STRAT_mod*RAWMATERIAL,
               data = fit_df,
  family = Gamma(link = "log"),
  #prior = CE_prior,
  cores = getOption("mc.cores", parallel::detectCores()),
  chains = 4,
  iter = 4000,
  seed = 11223307
)
```

```{r}
#| include: false


pp_check(fit_CE_anova, type = "dens_overlay_grouped",
         group = "STRAT_mod")
pp_check(fit_CE_anova, type = "stat_grouped", 
         group = "STRAT_mod")
pp_check(fit_CE_anova, type = "scatter_avg_grouped",
         group = "STRAT_mod")

pp_check(fit_CE_anova, type = "dens_overlay_grouped", 
         group = "RAWMATERIAL")
pp_check(fit_CE_anova, type = "stat_grouped", 
         group = "RAWMATERIAL")
pp_check(fit_CE_anova, type = "scatter_avg_grouped",
         group = "RAWMATERIAL")

loo2 <- loo(fit_CE_anova, moment_match = T)
plot(loo2)
```

```{r}
fit_CE_anova |>
  epred_draws(
    newdata = distinct(fit_df, STRAT_mod, RAWMATERIAL)
    ) |>
  #filter(.epred < 3.5) |>
  ggplot() +
  stat_halfeye(aes(x = factor(STRAT_mod), y = .epred, fill = RAWMATERIAL),
               .width = c(.90, .5), scale = 0, linewidth = 1, point_size = 0.7,
               adjust = 0.8, width = 0.6,
               orientation = "vertical", point_interval = "median_qi")+
  facet_wrap(~RAWMATERIAL, scales = "free") +
  theme_minimal()+
  theme(legend.title = element_blank())+
  theme_classic(base_size = 18)+
  guides(color = "none")+
    theme(axis.text.x = 
          element_text(angle = 45, hjust = 1),
          text = element_text(size = 18),
          legend.position = "none") +
  ylab("Posterior Median Scar Density Index") + 
  xlab("Coastal-to-Terrestrial\nFoods") -> plot_CE2
```

```{r}
png("../results/figures/Figure10.png", width = 290, height = 220,
    units = "mm", res = 300)


ggarrange(
  plot_CE2, plot_CE1, nrow = 2,
  font.label = list(size = 25, face = "bold"),
  common.legend = FALSE, labels = c("A", "B"),
  widths = c(2, 1), heights = c(1.5, 1),
  label.y = c(0.98, 1.11),
  label.x = c(0.04, 0.04)
)

dev.off()
```

### Volume Calculation

```{r coreVolumeRemoved}
# Compute columetric reconstructions
df.flakes |>
  select(RAWMATERIAL, STRAT_mod, STRAT_modn, PLATFORMTHICKNESS, MAXTHICKNESS) |>
  group_by(RAWMATERIAL, STRAT_mod, STRAT_modn) |>
  na.omit() |>
  summarize(m_plat = mean(PLATFORMTHICKNESS),
            m_thick = mean(MAXTHICKNESS)) |>
  arrange(STRAT_mod, RAWMATERIAL) -> flake.vr

flake.vr |>
  left_join(df.cores) |>
  select(m_plat, m_thick,
         STRAT_mod, STRAT_modn,
         RAWMATERIAL, MAXLENGTH, MAXWIDTH, MAXTHICKNESS,
         FLAKEGENERATIONSTHICKNESS, FLAKEGENERATIONSLENGTH, FLAKEGENERATIONSWIDTH,
         SA_Ellipse, SCARCOUNT) |>
  na.omit() |>
  group_by(RAWMATERIAL, STRAT_mod) |>
  mutate(V = pi*(4/3)*(MAXLENGTH/2)*(MAXWIDTH/2)*(MAXTHICKNESS/2),
         VR = pi*(4/3)*((MAXLENGTH + (m_plat*FLAKEGENERATIONSLENGTH))/2)*
                       ((MAXWIDTH + (m_plat*FLAKEGENERATIONSWIDTH))/2)*
                       ((MAXTHICKNESS + (m_thick*FLAKEGENERATIONSTHICKNESS))/2),
         volume_removed = (V/VR)*100,
         
         SDI = SCARCOUNT/SA_Ellipse) |>
  select(STRAT_mod, STRAT_modn,
         RAWMATERIAL, V, VR, volume_removed, SDI, SA_Ellipse)-> cores.vr
```

```{r}
# Refine outliers and define priors and run bayesian model
lm_red <- cores.vr |>
  filter(V < 10000,
         V > 0,
         
         VR < 60000)

lm_red$STRAT_mod_s <- scale(lm_red$STRAT_mod, center = T, scale = T)


fit_df <- lm_red |>
  mutate(Utility_s = V/1000,
         Reduction_s = scale(VR, center = T, scale = T),
         STRAT_mod = factor(STRAT_mod))|>
  select(Utility_s, Reduction_s, STRAT_mod, STRAT_mod_s) |>
  na.omit()

# Gamma prior
my_prior <-

  # Intercept
  prior(normal(0.5, 1), class = Intercept)+
  
  # Polynomial factor 1
  prior(normal(0.5, 1), class = b, coef = "polyVR_s2rawEQTRUE1")+

  # Polynomial factor 2
  prior(normal(0.5, 0.5), class = b, coef = "polyVR_s2rawEQTRUE2")+

  # Group-level SDs
  prior(exponential(1), class = sd)+

  # Gamma shape
  prior(exponential(1), class = shape)


  
  
# Run Bayesian model with varying slopes
bayes_poly0 <- brm(Utility_s ~ 1 + poly(Reduction_s, 2, raw = TRUE) + RAWMATERIAL +
                   (0 + poly(Reduction_s, 2, raw = TRUE) | STRAT_mod),
              data = fit_df,
              family = Gamma(link = "log"),
              iter = 2000,
              chains = 2,
              seed = 7773163,
              control = list(adapt_delta = 0.95),
              #prior=my_prior,
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))

bayes_poly1 <- brm(Utility_s ~ 1 + STRAT_mod_s + poly(Reduction_s, 2, raw = TRUE) +
                   (0 + poly(Reduction_s, 2, raw = TRUE) | RAWMATERIAL),
              data = fit_df,
              family = Gamma(link = "log"),
              iter = 2000,
              chains = 2,
              seed = 77731633,
              control = list(adapt_delta = 0.95),
              #prior=my_prior,
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", parallel::detectCores()))


my_prior <-
  prior(normal(0,1), class = "b")+
  prior(lkj(2), class = "cor")+
  prior(exponential(1), class = "sd")+
  prior(gamma(0.1, 0.2), class = "shape")


bayes_poly2 <- brm(Utility_s ~ 1 + poly(Reduction_s, 2, raw = TRUE) + 
                   (0 + poly(Reduction_s, 2, raw = TRUE) | STRAT_mod/RAWMATERIAL),
              data = fit_df,
              family = Gamma(link = "log"),
              iter = 2000,
              chains = 4,
              seed = 77731634,
              control = list(adapt_delta = 0.99, max_treedepth = 15),
              prior=my_prior,
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", parallel::detectCores()))

bayes_poly21 <- brm(Utility_s ~ 1 + poly(Reduction_s, 2, raw = TRUE) + 
                      RAWMATERIAL +
                   (0 + poly(Reduction_s, 2, raw = TRUE) | STRAT_mod),
              data = fit_df,
              family = Gamma(link = "log"),
              iter = 2000,
              chains = 4,
              seed = 77731634,
              control = list(adapt_delta = 0.99, max_treedepth = 15),
              #prior=my_prior,
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", parallel::detectCores()))


bayes_poly3 <- brm(Utility_s ~ 1 + STRAT_mod_s + poly(Reduction_s, 2, raw = TRUE) + RAWMATERIAL,
              data = fit_df,
              family = Gamma(link = "log"),
              iter = 2000,
              chains = 2,
              seed = 77731635,
              control = list(adapt_delta = 0.95),
              #prior=my_prior,
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))

bayes_poly4 <- brm(Utility_s ~ 1 + STRAT_mod + poly(Reduction_s, 2, raw = TRUE) + RAWMATERIAL,
              data = fit_df,
              family = Gamma(link = "log"),
              iter = 2000,
              chains = 2,
              seed = 77731635,
              control = list(adapt_delta = 0.95),
              #prior=my_prior,
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))


bayes_simp1 <- brm(Utility_s ~ 1 + STRAT_mod_s + Reduction_s +
                   (0 + Reduction_s | RAWMATERIAL),
              data = fit_df,
              family = Gamma(link = "log"),
              iter = 2000,
              chains = 2,
              seed = 203826407,
              control = list(adapt_delta = 0.95),
              #prior=my_prior,
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))

bayes_simp2 <- brm(Utility_s ~ 1 + STRAT_mod_s + Reduction_s + RAWMATERIAL,
              data = fit_df,
              family = Gamma(link = "log"),
              iter = 2000,
              chains = 2,
              seed = 203826407,
              control = list(adapt_delta = 0.95),
              #prior=my_prior,
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))

```

```{r}
#| include: false

# Validate model with posterior checks
loo0 <- loo(bayes_poly0)
loo1 <- loo(bayes_poly1)
loo2 <- loo(bayes_poly2)
loo3 <- loo(bayes_poly3)
loo4 <- loo(bayes_poly4)
loo21 <- loo(bayes_poly21)

loo_s1 <- loo(bayes_simp1)
loo_s2 <- loo(bayes_simp2)

loo_compare(loo0, loo1, loo2, loo3, loo4, loo_s1, loo_s2, loo21)



pp_check(bayes_poly2, type = "dens_overlay")
pp_check(bayes_poly2, type = "stat")
pp_check(bayes_poly2, type = "stat_grouped", group = "RAWMATERIAL")
pp_check(bayes_poly2, type = "scatter_avg_grouped", group = "RAWMATERIAL")

pp_check(bayes_poly2, type = "stat_grouped", group = "STRAT_mod")
pp_check(bayes_poly2, type = "scatter_avg_grouped", group = "STRAT_mod")
```

```{r}

x_seq <- seq(min(fit_df$Reduction_s, na.rm = TRUE),
             max(fit_df$Reduction_s, na.rm = TRUE)-2.5,
             length.out = 100)

draws <- as_draws_df(bayes_poly2)

# All combinations of grouping levels
slope_draws <- expand_grid(
  draws,
  Reduction_s = x_seq,
  STRAT_mod = unique(fit_df$STRAT_mod)
) |>
  mutate(
    eta = b_Intercept +
          b_polyReduction_s2rawEQTRUE1 * Reduction_s +
          b_polyReduction_s2rawEQTRUE2 * Reduction_s^2,

    slope = exp(eta) *
            (b_polyReduction_s2rawEQTRUE1 +
             2 * b_polyReduction_s2rawEQTRUE2 * Reduction_s)
  )


slope_summary <- slope_draws |>
  group_by(Reduction_s) |>
  summarise(
    mean = mean(slope),
    lwr = quantile(slope, 0.05),
    upr = quantile(slope, 0.95),
    .groups = "drop"
  )


  ggarrange(
  core_conard,
  font.label = list(size = 25, face = "bold"),
  widths = c(2, 1), heights = c(1.5, 1),
  label.y = c(1, 1.2),
  label.x = c(0.05, 0.05)
  )

dev.off()
ggplot(slope_summary, aes(Reduction_s, mean)) +
  geom_line(linewidth = 1) +
  geom_ribbon(aes(ymin = lwr, ymax = upr),
              alpha = 0.25) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  labs(
    x = "Reduction_s",
    y = "Marginal slope of Utility",
    title = "Marginal effect of Reduction on Utility"
  ) +
  theme_minimal() 

```

```{r}
x_seq <- seq(min(fit_df$Reduction_s, na.rm = TRUE),
             max(fit_df$Reduction_s, na.rm = TRUE)-2.5,
             length.out = 100)

draws <- as_draws_df(bayes_poly2)
ranef <- ranef(bayes_poly2)$`STRAT_mod:RAWMATERIAL`[,,]


groups_to_plot <- fit_df |>
  count(STRAT_mod) |>
  rename("group" = "STRAT_mod") |>
  arrange(desc(n)) |>
  pull(group)



slope_group_draws <- map_dfr(groups_to_plot, function(g) {

  
  g1 <- paste0("r_STRAT_mod[", g, ",polyReduction_s2rawEQTRUE1]")
  g2 <- paste0("r_STRAT_mod[", g, ",polyReduction_s2rawEQTRUE2]")

  expand_grid(
    draws,
    Reduction_s = x_seq
  ) |>
    mutate(
      group = g,

      b1g = b_polyReduction_s2rawEQTRUE1 + .data[[g1]],
      b2g = b_polyReduction_s2rawEQTRUE2 + .data[[g2]],

      eta = b_Intercept +
            b1g * Reduction_s +
            b2g * Reduction_s^2,

      slope = exp(eta) * (b1g + 2 * b2g * Reduction_s)
    )
})


slope_group_summary <- slope_group_draws |>
  group_by(group, Reduction_s) |>
  summarise(
    mean = mean(slope),
    lwr = quantile(slope, 0.05),
    upr = quantile(slope, 0.95),
    .groups = "drop"
  )

png("../results/figures/Figure13a.png", width = 290, height = 120,
    units = "mm", res = 300)


ggplot(slope_group_summary,
       aes(Reduction_s, mean, color = group)) +
  geom_line(linewidth = 1) +
  geom_ribbon(aes(ymin = lwr, ymax = upr, fill = group),
              alpha = 0.25) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  labs(
    x = "Reduction (Scaled)",
    y = expression(Delta~"Utility-to-Reduction"),
    color = "Ratio"
  ) +
  theme_minimal()+
  guides(fill = "none")

dev.off()
```

```{r}
# Probability slopes are greater than 0
positive_prob <- slope_group_draws |>
  group_by(group, Reduction_s) |>
  summarise(
    Pr_positive = mean(slope > 0),
    .groups = "drop"
  ) |> 
  
  filter(Pr_positive > 0.89) |>
  group_by(group) |>
  summarize(max = max(Reduction_s))

#positive_prob

# Expected slope for each strat at specified reduction value
em_slopes_resp <- emtrends(
  bayes_poly2,
  ~ STRAT_mod,
  var = "Reduction_s",
  # Compute from the minimum significant slope for all strats
  at = list(Reduction_s = c(min(positive_prob$max))),
  type = "response",
  allow_new_levels = TRUE,
  re_formula = NULL
)
png("../results/figures/Figure13b.png", width = 290, height = 120,
    units = "mm", res = 300)

plot(em_slopes_resp)+
  xlab(expression(Delta*"Utility-to-Reduction"))+
  ylab("Ratio")

dev.off()
pairs(em_slopes_resp)


# Expected Utility for each strat at specified reduction value
em_slopes_resp <- emmeans(
  bayes_poly2,
  ~ STRAT_mod,
  var = "Reduction_s",
  # Compute from the minimum significant slope for all strats
  at = list(Reduction_s = c(min(positive_prob$max))),
  type = "response",
  allow_new_levels = TRUE,
  re_formula = NULL
)
#plot(em_slopes_resp)
#pairs(em_slopes_resp)
```

```{r}
# This shows that, regardless of estimated cultural practice, the major effect on utility is the degree of coastal exploitation
newdata <- expand.grid(
  VR_s = seq(min(Bayes_ut1$VR_s), max(Bayes_ut1$VR_s), length.out = 200),
  STRAT_mod = c(as.numeric(unique(df$STRAT_mod))),
  RAWMATERIAL = unique(df$RAWMATERIAL)
) |>
  mutate(RAWMATERIAL = droplevels(RAWMATERIAL))

epreds <- add_epred_draws(bayes_poly2, newdata = newdata, ndraws = 1000,
                          allow_new_levels = TRUE)



epreds |>
  filter(.epred < 100) |>
  group_by(VR_s, RAWMATERIAL, STRAT_mod) |>
  median_qi(.epred, .width = 0.90) |>

ggplot(aes(x = VR_s, y = .epred, color = factor(STRAT_mod, ordered = TRUE),
           fill = factor(STRAT_mod, ordered = TRUE))) +
  geom_line(linewidth = 1) +
  geom_ribbon(aes(ymin = .lower, ymax = .upper), alpha = 0.2, color = NA) +
  facet_wrap(~ RAWMATERIAL, scales = "free") +
  scale_color_viridis_d() +
  scale_fill_viridis_d() +
  labs(
    x = "Reduction (standardized)",
    y = "Expected Utility",
    color = "",
    fill = ""
  ) + theme_minimal()+xlim(-2, 3.5)+
  theme(text = element_text(size= 20),
        legend.position = "none") +
  xlim(-1, 2)


```

```{r}
post_draws <- spread_draws(
  bayes_poly2,
  `b_Intercept`,
  `b_polyVR_s2rawEQTRUE1`, `b_polyVR_s2rawEQTRUE2`,
  
  `r_STRAT_mod`[Ratio,],
  `r_STRAT_mod:RAWMATERIAL`[Ratio_Raw,]

  ) |>
  
  mutate(b0 = `b_Intercept`,
         bx = `b_polyVR_s2rawEQTRUE1`,
         bx2 = `b_polyVR_s2rawEQTRUE2`,
         
         b1 = bx + `r_STRAT_mod` + `r_STRAT_mod:RAWMATERIAL`,
         b2 = bx2 + `r_STRAT_mod` + `r_STRAT_mod:RAWMATERIAL`,
         
         slope = b1 + (2 * b2),
         
         critical_pt = -1 * ((b1)/(2 * (b2))))


post_draws |>
  group_by(Ratio) |>
  median_qi(slope, .width = c(.5, .9)) |>
  
  ggplot(aes(y = factor(Ratio, ordered = TRUE), x = slope, xmin = .lower, xmax = .upper)) +
  geom_pointinterval() +
  labs(
    x = "Posterior estimate of a",
    y = "STRAT:RAWMATERIAL",
    title = "Hierarchical posterior estimates of amplitude (a)"
  ) +
  theme_minimal()


post_draws |>
  group_by(Ratio_Raw) |>
  median_qi(slope, .width = c(.5, .9)) |>
  
  ggplot(aes(y = factor(Ratio_Raw, ordered = TRUE), x = slope, xmin = .lower, xmax = .upper)) +
  geom_pointinterval() +
  labs(
    x = "Posterior Slope Estimate",
    y = ""
  ) +
  theme_minimal()


```

```{r}
new_seq <- seq(min(Bayes_ut1$VR_s),
               max(Bayes_ut1$VR_s),
               length.out = 25)

post_draws |>
  mutate(draw = row_number()) |>
  
  tidyr::crossing(Reduction_s = new_seq) |>
  
  mutate(
    
    slope_x = b1 + ((2 * b2) * Reduction_s)
  
  ) |>
  filter(Reduction_s < 2, Reduction_s > 0) |>
  group_by(Ratio_Raw) |>
  
  median_qi(slope_x, .width = c(0.5,0.9)) |>
  mutate(Ratio_Raw = as.factor(Ratio_Raw)) |>
  
  ggplot(aes(x = slope_x, y = Ratio_Raw)) +
    geom_pointinterval(aes(xmin = .lower, xmax = .upper)) +
    labs(
      x = "Median Slope Values",
      y = ""
    ) 
    theme_minimal() +
  scale_y_discrete(labels = c("Quartz", "Quartzite", "Silcrete"))+
  theme(text = element_text(size= 20),
        legend.position = "none")

  
  
post_draws |>
  mutate(draw = row_number()) |>
  
  tidyr::crossing(Reduction_s = new_seq) |>
  
  mutate(
    
    slope_x = b1 + ((2 * b2) * Reduction_s)
  
  ) |>
  filter(Reduction_s < 1, Reduction_s > -1) |>
  group_by(Raw) |>
  summarize(mean = mean(slope_x > 0))
```
