---
title: "SBF_Scrapers"
format: html
editor: visual
---

```{r}
library(ggplot2)
library(forcats)
library(ggpubr)
library(ggridges)
library(cowplot)
library(ggforce)
library(here)

library(infer)
#library(rcompanion)
library(purrr)
#library(rcompanion)
library(viridis)

library(scales)
library(stringr)

# To generate tables
library(gtsummary)
library(gt)
library(broom)
library(broom.mixed)

library(stargazer)
library(kableExtra)

# To tidy the data
library(tidyr)
library(tidyverse)
library(dplyr)
library(forcats)
library(tidybayes)

# Bayesian models
library(brms)
library(emmeans)
library(loo)
library(BayesFactor)
library(posterior)
```

```{r ScraperRetouchFormula}
# Calculate scraper retouch intensity
scraper_red <- function(L, D, a, b){
  
  t = D * sin(a)
  D3 = D * cos(a)
  D1 = t/(sin(b))
  D4 = (t * cos(b))/(sin(b))
  
  D2 = D4 - D3
  
  B = t * (sin(b)) # define base B to find height (which is also D1)
  
  h = sin(b) * ((t*(cos(b)/sin(b))) - (D*cos(a)))
  
  A =  0.5 * B * h# find values of area now
  
  RE = L*((D^2)/2)*((sin(a*(pi/180))^2 * 
                       (cos(b*(pi/180))/sin(b*(pi/180)))) - 
                      (sin(a*(pi/180)) * cos(a*(pi/180))))
  
  
  output <- tibble(Reduction = RE)
  
  return(output)
  
  
}
```

```{r ReadData}
#| message: false
#| warning: false

# Read and clean data
df_sum24 <- read.csv(here::here("data", "AG_Summer2024_SBF_Final.csv")) |>
  select(-c('X')) |>
  filter(RAWMATERIAL != "BWA UPPER 1" &
           RAWMATERIAL %in% c("Quartz", "Quartzite", "Silcrete")) |>
  mutate(STRAT_mod = ifelse(STRAT %in% c("5"), "Terrestrial",
                     ifelse(STRAT %in% c("4a", "4b"), "Mixed", "Coastal"))) |>
  mutate(STRAT = factor(STRAT),
         STRAT_mod = factor(STRAT_mod))

df_sum25 <- read.csv(here::here("data", "AG_Summer2025_SBF_Final.csv")) |>
  filter(RAWMATERIAL != "BWA UPPER 1" &
           RAWMATERIAL %in% c("Quartz", "Quartzite", "Silcrete")) |>
  mutate(STRAT_mod = ifelse(STRAT %in% c("5"),"Terrestrial",
                     ifelse(STRAT %in% c("4a", "4b"), "Mixed", "Coastal"))) |>
  mutate(STRAT = factor(STRAT),
         STRAT_mod = factor(STRAT_mod)) |>
  
  select(-c(X))

# student's dataframe
df_One <- read_csv(here::here("data", "DataSheet_1.csv"))|>
  mutate(STRAT = tolower(Layer),
         
         PLATFORMWIDTH = parse_number("Platform Width"),
         PLATFORMTHICKNESS = parse_number("Platform Thickness"),
         MAXLENGTH = parse_number("Maximum Length"),
         TECHLENGTH = parse_number("Technological Length"),
         MAXWIDTH = parse_number("Maximum Width"),
         TECHWIDTH = parse_number("Technological Width"),
         MAXTHICKNESS = parse_number("Thickness"),
         MASS = parse_number("Mass"))

df_One <- df_One[1:289,]

df_One_flakes <- df_One |>
  
  add_column(OTHERUNIT = NA, .before = "Raw Material") |>

  rename(SITE = Site, UNIT = Unit, NAMED_ID = `Other Name`,
         RAWMATERIAL = `Raw Material`, CORTEX = `Cortex Percent`,
         CORTEXTYPE = `Cortex Origin`, ARTIFACTCLASS = `Artifact class`,
         COMPLETENESS = Complete, PLATFORM = `Platform?`,
         FLAKEINITIATION = Initiated, FLAKETERMINATION = Termination,
         FLAKEGEOMETRY = `Flake Geometry`, PLATFORMPREP = `Platform Preparation`,
         PLATABRASION = PlatformAbrasion, 
         STAGE = `Flaking Stage`) |>
  
  select(-c(Layer, Notes, Photo,
            `Platform Width`:`Platform Thickness`, `Maximum Length`:Mass)) |>
  
  mutate(#STRAT = ifelse(STRAT == "3a", "3", # combine strat 3a and 3b
          #            ifelse(STRAT == "3b", "3", 
           #                  ifelse(STRAT == "5a", "5", STRAT))),
         STRAT_mod = ifelse(STRAT %in% c("5"),"Terrestrial",
                     ifelse(STRAT %in% c("4a", "4b"), "Mixed", "Coastal"))) |>
  mutate(STRAT = factor(STRAT),
         STRAT_mod = factor(STRAT_mod)) |>
  
  relocate(STRAT, .before = "UNIT") |>
  relocate(CORTEXTYPE, .before = "ARTIFACTCLASS")
  
  

# student's Dataframe
df_Two <- read_csv(here::here("data", "DataSheet_2.csv")) |>
  
  rename(SITE = Site, STRAT = Layer, UNIT = Unit, NAMED_ID = `Other Name`,
         RAWMATERIAL = `Raw Material`, CORTEX = `Cortex Percent`,
         ARTIFACTCLASS = `Artifact class`, CORTEXTYPE = `Cortex Origin`,
         COMPLETENESS = Complete, PLATFORM = `Platform?`,
         FLAKEINITIATION = Initiated, FLAKETERMINATION = Termination,
         FLAKEGEOMETRY = `Flake Geometry`, PLATFORMPREP = `Platform Preparation`,
         PLATABRASION = `PlatformAbrasion`, PLATFORMWIDTH = `Platform Width`,
         PLATFORMTHICKNESS = `Platform Thickness`, STAGE = `Flaking Stage`,
         MAXLENGTH = `Maximum Length`, TECHLENGTH = `Technological Length`,
         MAXWIDTH = `Maximum Width`, TECHWIDTH = `Technological Width`,
         MAXTHICKNESS = Thickness, MASS = Mass) |>
  
  select(-c(`...2`,Notes:Photo))

df_Two_flakes <- df_Two |>
  
  add_column(OTHERUNIT = NA, .before = "RAWMATERIAL") |>
  
  mutate(STRAT_mod = ifelse(STRAT %in% c("5"),"Terrestrial",
                     ifelse(STRAT %in% c("4a", "4b"), "Mixed", "Coastal"))) |>
  mutate(STRAT = factor(STRAT),
         STRAT_mod = factor(STRAT_mod))




df_Two_flakes <- df_Two_flakes[1:421,] |>
  relocate(CORTEXTYPE, .before = "ARTIFACTCLASS")
  

df_students <- rbind(df_Two_flakes, df_One_flakes)


df <- rbind(df_sum24, df_sum25) |>
  merge(df_students, all = T) |>
  mutate(TECHLENGTH = as.numeric(TECHLENGTH),
         MAXWIDTH = as.numeric(MAXWIDTH),
         MAXTHICKNESS = as.numeric(MAXTHICKNESS)) |>
  filter(STRAT %in% c("1", "2", "3a", "3b", "3", "4a", "4b", "5")) |>
  
  mutate(ARTIFACTCLASS = ifelse(ARTIFACTCLASS == "flake", "Flake",
                         ifelse(ARTIFACTCLASS == "blade", "Flake",
                         ifelse(ARTIFACTCLASS == "Flake/Blade", "Flake",
                         ifelse(ARTIFACTCLASS == "Fragment", "Flake",
                                                     ARTIFACTCLASS)))),
         
         RAWMATERIAL = as.factor(
           ifelse(RAWMATERIAL == "Silcrete flake", "Silcrete",
                              ifelse(RAWMATERIAL == "OTHER", "Other",
                                     RAWMATERIAL))),
         
         CORTEX = ifelse(CORTEX == "10-40%", "11-40%",
                  ifelse(CORTEX == "90-99%", "91-99%",
                  ifelse(CORTEX == "60-90%", "61-90%",
                  ifelse(CORTEX == "40-60%", "41-60%",
                         CORTEX)))),
         
         STRAT_mod = ifelse(STRAT == "1", 27.2,
                     ifelse(STRAT == "2", 37.1,
                     ifelse(STRAT == "3a", 49.8,
                     ifelse(STRAT == "3b", 29.6,
                     ifelse(STRAT == "4a", 26.6,
                     ifelse(STRAT == "4b", 25.5,
                     ifelse(STRAT == "5", 8.4, 0))))))),
         
         STRAT_modn = ifelse(STRAT %in% c("5"),"Pre-Megamidden",
                     ifelse(STRAT %in% c("4a", "4b"), "Transitional", 
                            "Megamidden")),
         STRAT_modn = fct_relevel(STRAT_modn, 
                                  c("Pre-Megamidden", "Transitional",
                                    "Megamidden"))) |>
  
  filter(RAWMATERIAL %in% c("Quartz", "Quartzite", "Silcrete"),
         CORTEX != "\\",
         MAXWIDTH < 1250,
         MASS < 300)



# take average core flake scar length
df |>
  dplyr::filter(ARTIFACTCLASS=="Core") |>
  group_by(RAWMATERIAL, STRAT) |>
  summarize(Ave_FlakeLength = mean(LENGHTLONGESTFLAKESCAR)) -> core_size


# set values for small, medium, and large slug effect sizes

small <- 5.18


# Subset data by flakes and flake variables
core_bind <- full_join(core_size, df) |>
  filter(ARTIFACTCLASS == "Flake" & COMPLETENESS == "Complete") |>
  group_by(RAWMATERIAL, STRAT) |>
  mutate(Utility_small = TECHLENGTH*(TECHLENGTH - small),
         
         Transport_small = Utility_small/((MAXTHICKNESS/TECHLENGTH)*TECHLENGTH^3),
         
         Reduction = TECHLENGTH/Ave_FlakeLength) |>
  select(any_of(names(df_students))) -> df.flakes

# Subset data by cores and core variables
df.cores <- df |>
  filter(ARTIFACTCLASS == "Core" & CORECOMPLETENESS == "Complete") |>
  mutate(SA_Ellipse = (4*pi)*
           ((((((MAXLENGTH/2)*(MAXWIDTH/2))^1.6075)+
           (((MAXLENGTH/2)*(MAXTHICKNESS/2))^1.6075)+
           (((MAXWIDTH/2)+(MAXTHICKNESS/2))^1.6075))/3)^(1/1.6075)))

# Subset data by retouch and retouch variables
df.retouch <- df |>
  filter(ARTIFACTCLASS == "RetouchedTool" & RAWMATERIAL != "BWA UPPER 1" &
           COMPLETENESS == "Complete") |>
  mutate(Utility_small = TECHLENGTH*(TECHLENGTH - small),
         
         Transport_small = Utility_small/((MAXTHICKNESS/TECHLENGTH)*TECHLENGTH^3))

# Read tabulated data from previous publications (i.e. Jerardino & Yates)
sbf_df <- read.csv(here::here("data", "SBF_ToolType.csv"))
sbf_un <- read.csv(here::here("data", "SBF_ToolType_unmod.csv"))
```

## Scraper Utility to Retouch

```{r scraperRetouchIntensity}
# Define a database for scraper retouch
df.scrap <- df.retouch |>
  filter(RETOUCHEDPIECETYPOLOGY == "SideScraper" | 
           RETOUCHEDPIECETYPOLOGY == "EndScraper" |
           RETOUCHEDPIECETYPOLOGY == "Side-EndScraper") |>
  select("SCRAPERRETOUCHHEIGHT1","SCRAPERRETOUCHHEIGHT2","SCRAPERRETOUCHHEIGHT3",
         "SCRAPERRETOUCHANGLE1","SCRAPERRETOUCHANGLE2","SCRAPERRETOUCHANGLE3",
         "SCRAPERDORSALANGLE1","SCRAPERDORSALANGLE2","SCRAPERDORSALANGLE3",
         "SCRAPERRETOUCHLENGTH","SCRAPERMAXTHICKNESS",
         
         "SCRAPERRETOUCHHEIGHT1", "SCRAPERRETOUCHHEIGHT2", "SCRAPERRETOUCHHEIGHT3",
         
         "MAXLENGTH", "MAXWIDTH",
         
         "RAWMATERIAL", "STRAT", "STRAT_mod", "MASS",
         
         Utility_small:Transport_small) |>
  na.omit() |>
  mutate(RET_INT = round(((SCRAPERRETOUCHHEIGHT1+
                            SCRAPERRETOUCHHEIGHT2+
                            SCRAPERRETOUCHHEIGHT3)/SCRAPERMAXTHICKNESS)*
                           SCRAPERRETOUCHLENGTH,2),
         SA = MAXLENGTH*MAXWIDTH)


# Preprocess data to enter into custom function to calculate scraper reduction
scrap.red <- df.scrap |>
  na.omit() |>
  mutate(D = (SCRAPERRETOUCHHEIGHT1+SCRAPERRETOUCHHEIGHT2+SCRAPERRETOUCHHEIGHT3)/3,
         a = (SCRAPERRETOUCHANGLE1+SCRAPERRETOUCHANGLE2+SCRAPERRETOUCHANGLE3)/3,
         b = (SCRAPERDORSALANGLE1+SCRAPERDORSALANGLE2+SCRAPERDORSALANGLE3)/3) |>
  rename(L = SCRAPERRETOUCHLENGTH) |>
  mutate(RETOUCH = scraper_red(L, D, a, b)$Reduction)

# Export for R shiny app
scrap_export <- scrap.red |> 
  mutate(Rem.Weight = MASS,
         Max.thick = SCRAPERMAXTHICKNESS,
         Mean.t = mean(SCRAPERRETOUCHHEIGHT1+
                         SCRAPERRETOUCHHEIGHT2+
                         SCRAPERRETOUCHHEIGHT3),
         GIUR = RETOUCH) |>
  select(Rem.Weight, Max.thick, Mean.t, GIUR)

write.csv(scrap_export, here::here("data", "SBF_Scrap_Input.csv"))
```

```{r}
scrap_pred <- read_csv(here::here("data", "SBF_Scrap_Pred.csv")) |>
  select(`Percent.Consumed`) |>
  mutate(UTILITY_small = scrap.red$Utility_small,
         STRAT_mod = scrap.red$STRAT_mod,
         RAWMATERIAL = scrap.red$RAWMATERIAL
         )|>
  rename(RETOUCH = Percent.Consumed)
```

```{r}
# Refine outliers and define priors and run bayesian model
lm_red <- scrap_pred

lm_red$STRAT_mod_s <- scale(lm_red$STRAT_mod, center = T, scale = T)

fit_df <- lm_red |>
  mutate(Utility_s = UTILITY_small/100,
         Reduction_s = RETOUCH/100,
         STRAT_mod = factor(STRAT_mod)) |>
  select(Reduction_s, Utility_s, STRAT_mod, STRAT_mod_s, RAWMATERIAL) |>
  na.omit()

```

##### Nonlinear Models

```{r}
nlform0 <- bf(Utility_s ~ a * exp(-b * Reduction_s),
             a ~ 1, 
             b ~ 1,
             nl = TRUE)

nlform1 <- bf(Utility_s ~ a * exp(-b * Reduction_s),
             a ~ 1 + (1 | STRAT_mod/RAWMATERIAL), 
             b ~ 1 + (1 | STRAT_mod/RAWMATERIAL),
             nl = TRUE)

nlform2 <- bf(Utility_s ~ a * exp(-b * Reduction_s),
             a ~ 1 + RAWMATERIAL + (1 | STRAT_mod), 
             b ~ 1 + RAWMATERIAL + (1 | STRAT_mod),
             nl = TRUE)

nlform3 <- bf(Utility_s ~ a * exp(-b * Reduction_s),
             a ~ 1 + (1 | STRAT_mod), 
             b ~ 1 +(1 | STRAT_mod),
             nl = TRUE)

nlform4 <- bf(Utility_s ~ a * exp(-b * Reduction_s),
             a ~ 1 + STRAT_mod_s + (1 | RAWMATERIAL),
             b ~ 1 + STRAT_mod_s + (1 | RAWMATERIAL),
             nl = TRUE)

nlform5 <- bf(Utility_s ~ a * exp(-b * Reduction_s),
             a ~ 1 + STRAT_mod_s,
             b ~ 1 + STRAT_mod_s,
             nl = TRUE)

nlform6 <- bf(Utility_s ~ a * exp(-b * Reduction_s),
             a ~ 1 + STRAT_mod_s + RAWMATERIAL,
             b ~ 1 + STRAT_mod_s + RAWMATERIAL,
             nl = TRUE)

nlform7 <- bf(Utility_s ~ a * exp(-b * Reduction_s),
             a ~ 1 + STRAT_mod + RAWMATERIAL,
             b ~ 1 + STRAT_mod + RAWMATERIAL,
             nl = TRUE)

priors <- c(
  prior(lognormal(log(1), 0.5), nlpar = "a"),
  prior(lognormal(log(1), 0.5), nlpar = "b"),
  prior(exponential(1), class = "sigma")
)


bayes_prior0 <- brm(nlform0,
              data = fit_df,
              family = lognormal(),
              iter = 2000,
              chains = 2,
              seed = 77779777,
              control = list(adapt_delta = 0.95),
              prior=priors,
              sample_prior = "only",
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))


bayes_prior1 <- brm(nlform1,
              data = fit_df,
              family = lognormal(),
              iter = 2000,
              chains = 2,
              seed = 17770777,
              control = list(adapt_delta = 0.95),
              prior=priors,
              sample_prior = "only",
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))

bayes_prior2 <- brm(nlform2,
              data = fit_df,
              family = lognormal(),
              iter = 2000,
              chains = 2,
              seed = 11117708887,
              control = list(adapt_delta = 0.95),
              prior=priors,
              sample_prior = "only",
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))

bayes_prior3 <- brm(nlform3,
              data = fit_df,
              family = lognormal(),
              iter = 2000,
              chains = 2,
              seed = 12223308887,
              control = list(adapt_delta = 0.95),
              prior=priors,
              sample_prior = "only",
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))

bayes_prior4 <- brm(nlform4,
              data = fit_df,
              family = lognormal(),
              iter = 2000,
              chains = 2,
              seed = 17788467387,
              control = list(adapt_delta = 0.95),
              prior=priors,
              sample_prior = "only",
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))

bayes_prior5 <- brm(nlform5,
              data = fit_df,
              family = lognormal(),
              iter = 2000,
              chains = 2,
              seed = 17788467387,
              control = list(adapt_delta = 0.95),
              prior=priors,
              sample_prior = "only",
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))

bayes_prior6 <- brm(nlform6,
              data = fit_df,
              family = lognormal(),
              iter = 2000,
              chains = 2,
              seed = 17788467387,
              control = list(adapt_delta = 0.95),
              prior=priors,
              sample_prior = "only",
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))

prior_draws <- add_epred_draws(bayes_prior0, newdata = fit_df, ndraws = 150)
pp_clean <- prior_draws |>
  filter(!is.infinite(.epred), !is.na(.epred), abs(.epred) < 1e6)

p1 <- ggplot(pp_clean, aes(x = Reduction_s, y = .epred, group = .draw)) +
  geom_line(alpha = 0.1) +
  labs(title = "Prior Predictive (linear y)", x = "Retouch Intensity (scaled)", y = "Utility")


p2 <- ggplot(pp_clean, aes(x = Reduction_s, y = .epred, group = .draw)) +
  geom_line(alpha = 0.1) +
  scale_y_continuous(trans = "pseudo_log") +   # or use scale_y_log10() if all >0
  labs(title = "Prior Predictive (log y)", x = "Retouch Intensity (scaled)", y = "Utility (log scale)")

p1; p2

ggplot(pp_clean, aes(x = Reduction_s, y = .epred, 
                        group = .draw)) +
  geom_line(alpha = 0.2) +
  #facet_wrap(~RAWMATERIAL) +
  labs(title = "Prior Predictive by STRAT_mod",
       x = "Retouch Intensity (scaled)",
       y = "Predicted Utility (prior)") +
  theme_minimal() + ylim(0, 1500)

bayes_nl0 <- update(bayes_prior0, sample_prior = "no")
bayes_nl1 <- update(bayes_prior1, sample_prior = "no")
bayes_nl2 <- update(bayes_prior2, sample_prior = "no")
bayes_nl3 <- update(bayes_prior3, sample_prior = "no")
bayes_nl4 <- update(bayes_prior4, sample_prior = "no")
bayes_nl5 <- update(bayes_prior5, sample_prior = "no")
bayes_nl6 <- update(bayes_prior6, sample_prior = "no")
```

```{r}
loo_nl0 <- loo(bayes_nl0)
loo_nl1 <- loo(bayes_nl1)
loo_nl2 <- loo(bayes_nl2)
loo_nl3 <- loo(bayes_nl3)
loo_nl4 <- loo(bayes_nl4)
loo_nl5 <- loo(bayes_nl5)
loo_nl6 <- loo(bayes_nl6)

loo_compare(loo_nl0, loo_nl1, loo_nl2, loo_nl3, loo_nl4,
            loo_nl5, loo_nl6)
```

##### Linear Models

```{r}
# Define prior
my_prior <-

  # Intercept
  prior(normal(0.5, 1), class = Intercept)+
  
  # Fixed effect
  prior(normal(0.5, 1), class = b, coef = "polyRetouch_Intensity_s21")+
  
  prior(normal(0.5, 1), class = b, coef = "polyRetouch_Intensity_s22")+

  # Group-level SDs
  prior(exponential(1), class = sd)


  
  
# Run Bayesian model with varying slopes
bayes_scrap_poly <- brm(Utility_s ~ 1 + poly(Reduction_s, 2) + 
                          STRAT_mod_s +
                   (0 + poly(Reduction_s, 2) | RAWMATERIAL),
              data = fit_df,
              family = lognormal(),
              iter = 2000,
              chains = 2,
              seed = 37193751,
              control = list(adapt_delta = 0.95),
              #prior=my_prior,
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))


bayes_scrap_poly_RM <- brm(Utility_s ~ 1 + poly(Reduction_s, 2) + STRAT_mod_s +
                   (0 + poly(Reduction_s, 2) | STRAT_mod/RAWMATERIAL),
              data = fit_df,
              family = lognormal(),
              iter = 2000,
              chains = 2,
              seed = 371108732751,
              control = list(adapt_delta = 0.95),
              #prior=my_prior,
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))


my_prior <-

  # Intercept
  prior(normal(0.5, 1), class = Intercept)+
  
  # Fixed effect
  prior(normal(0.5, 1), class = b, coef = "Retouch_Intensity_s")+

  # Group-level SDs
  prior(exponential(1), class = sd)

bayes_scrap_simp <- brm(Utility_s ~ 1 + Reduction_s +
                   (0 + Reduction_s | STRAT_mod),
              data = fit_df,
              family = lognormal(),
              iter = 2000,
              chains = 4,
              seed = 115864237,
              control = list(adapt_delta = 0.99, max_treedepth = 15),
              #prior=my_prior,
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))


```

```{r}
#| include: false
# Check posterior distirbutions and compare models
# simpler model (linear) fits best
loo_poly <- loo(bayes_scrap_poly)
loo_simp <- loo(bayes_scrap_simp)
loo_poly_RM <- loo(bayes_scrap_poly_RM)

loo_compare(loo_poly, loo_poly_RM, loo_simp,
            loo_nl0, loo_nl1, loo_nl2, loo_nl3, loo_nl4,
            loo_nl5, loo_nl6)

# bayes_scrap_poly_RM is the best fit

pp_check(bayes_scrap_poly_RM)
pp_check(bayes_scrap_poly_RM, type = "scatter_avg")
```

```{r}
x_seq <- seq(min(fit_df$Reduction_s, na.rm = TRUE),
             max(fit_df$Reduction_s, na.rm = TRUE),
             length.out = 50)

# All combinations of grouping levels
newdat <- expand_grid(
  Reduction_s = x_seq,
  STRAT_mod_s = unique(fit_df$STRAT_mod_s),
  RAWMATERIAL = unique(fit_df$RAWMATERIAL)
)

draws <- as_draws_df(bayes_scrap_simp)

slope_draws <- expand_grid(
  draws,
  Reduction_s = x_seq,
  STRAT_mod = unique(fit_df$STRAT_mod)
)

# Get fitted values (posterior draws of the mean)
preds <- fitted(
  bayes_scrap_simp,       # your Gamma(log) model
  newdata = newdat,
  re_formula = NULL,    # include group-level effects
  summary = FALSE,       # return full posterior draws
  allow_new_levels = TRUE
)

# Add to the grid and summarize
pred_summary <- newdat |>
  bind_cols(as_tibble(t(preds))) |>
  pivot_longer(cols = starts_with("V"), values_to = "Retouch_pred") |>
  group_by(RAWMATERIAL, Reduction_s) |>
  summarise(
    mean = mean(Retouch_pred),
    lower = quantile(Retouch_pred, 0.05),
    upper = quantile(Retouch_pred, 0.95),
    .groups = "drop"
  )



```

```{r}
x_seq <- seq(min(fit_df$Reduction_s, na.rm = TRUE),
             max(fit_df$Reduction_s, na.rm = TRUE),
             length.out = 100)

draws <- as_draws_df(bayes_scrap_simp)
ranef <- ranef(bayes_scrap_simp)$`STRAT_mod`[,,]


groups_to_plot <- fit_df |>
  count(STRAT_mod) |>
  rename("group" = "STRAT_mod") |>
  arrange(desc(n)) |>
  pull(group)



slope_group_draws <- map_dfr(groups_to_plot, function(g) {

  
  g1 <- paste0("r_STRAT_mod[", g, ",Reduction_s]")

  expand_grid(
    draws,
    Reduction_s = x_seq
  ) |>
    mutate(
      group = g,

      eta = b_Reduction_s + .data[[g1]],
    )
})


slope_group_summary <- slope_group_draws |>
  group_by(group, Reduction_s) |>
  summarise(
    mean = mean(eta),
    lwr = quantile(eta, 0.05),
    upr = quantile(eta, 0.95),
    .groups = "drop"
  )

png(here::here("results/figures", "Figure14a.png"), width = 290, height = 120,
    units = "mm", res = 300)

ggplot(slope_group_summary,
       aes(Reduction_s, mean, color = group)) +
  geom_line(linewidth = 1) +
  geom_ribbon(aes(ymin = lwr, ymax = upr, fill = group),
              alpha = 0.25) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  labs(
    x = "Reduction (Scaled)",
    y = expression(Delta~"Utility-to-Reduction"),
    color = "Ratio"
  ) +
  theme_minimal()+
  guides(fill = "none")

dev.off()
```

```{r}
# Probability slopes are greater than 0
negative_prob <- slope_group_draws |>
  group_by(group, Reduction_s) |>
  summarise(
    Pr_negative = mean(eta < 0),
    .groups = "drop"
  ) |> 
  
  filter(Pr_negative > 0.89) |>
  group_by(group) |>
  summarize(max = max(Reduction_s))

#negative_prob

# Expected slope for each strat at specified reduction value
em_slopes_resp <- emtrends(
  bayes_scrap_simp,
  ~ STRAT_mod,
  var = "Reduction_s",
  # Compute from the minimum significant slope for all strats
  at = list(Reduction_s = c(min(negative_prob$max))),
  type = "response",
  allow_new_levels = TRUE,
  re_formula = NULL
)

png(here::here("results/figures", "Figure14b.png"), width = 290, height = 120,
    units = "mm", res = 300)

plot(em_slopes_resp)+
  xlab(expression(Delta*"Utility-to-Reduction"))+
  ylab("Ratio")


dev.off()
#pairs(em_slopes_resp)

# Expected Utility for each strat at specified reduction value
em_slopes_resp <- emmeans(
  bayes_scrap_simp,
  ~ STRAT_mod,
  var = "Reduction_s",
  # Compute from the minimum significant slope for all strats
  at = list(Reduction_s = c(min(negative_prob$max))),
  type = "response",
  allow_new_levels = TRUE,
  re_formula = NULL
)
#plot(em_slopes_resp)
#pairs(em_slopes_resp)
```
